#### To perform the feature encoding technique and determine whether the customer will purchase the product or not based on demographic data


##### Step 1: Import all the necessary libraries

In [990]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

import  joblib

from    sklearn.model_selection  import  train_test_split
from    sklearn.preprocessing    import  StandardScaler
from    sklearn.linear_model     import  LogisticRegression
from    sklearn.metrics          import  accuracy_score, confusion_matrix, classification_report

#### Step 2: Load the Dataset

In [991]:
df = pd.read_csv("Social_Network_Ads.csv")

In [992]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

#### OBSERVATIONS:

1.  The above dataset explains about the details of the customer whther they will purchase the product or not.

#### Step 3: Perform the Data Exploration

In [993]:
#### get the first five rows of the dataset

print(df.head())

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [994]:
#### get the description about all the columns used in the dataset

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
None

In [995]:
#### get the descriptive summary statistics about the dataset

print(df.describe())

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [996]:
#### get the count of all the categories in 'Purchased' Column

df['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

#### OBSERVATIONS:

1. The above dataset has more number of 0s than the 1s . So it is an imbalanced dataset.

In [997]:
#### Perform the resampling on the imbalanced dataset to make it balanced

from  sklearn.utils  import resample

df_majority = df[df['Purchased'] == 0]

df_minority = df[df['Purchased'] == 1]

In [998]:
#### perform the upsamling on the minority class

df_minority_upsample = resample(
    df_minority                                  ,
    replace= True                                ,
    n_samples= len(df_majority)                  ,
    random_state=42
)

In [999]:
df_minority_upsample

      User ID  Gender  Age  EstimatedSalary  Purchased
340  15588080  Female   53           104000          1
320  15774872  Female   52           138000          1
48   15727696    Male   30           135000          1
347  15768151  Female   54           108000          1
283  15663249  Female   52            21000          1
..        ...     ...  ...              ...        ...
364  15654456    Male   42           104000          1
20   15649487    Male   45            22000          1
331  15589715  Female   48           119000          1
373  15708791    Male   59           130000          1
223  15593715    Male   60           102000          1

[257 rows x 5 columns]

In [1000]:
df_new = pd.concat([df_majority, df_minority_upsample])

In [1001]:
df_new

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
364  15654456    Male   42           104000          1
20   15649487    Male   45            22000          1
331  15589715  Female   48           119000          1
373  15708791    Male   59           130000          1
223  15593715    Male   60           102000          1

[514 rows x 5 columns]

In [1002]:
df = df_new

In [1003]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
364  15654456    Male   42           104000          1
20   15649487    Male   45            22000          1
331  15589715  Female   48           119000          1
373  15708791    Male   59           130000          1
223  15593715    Male   60           102000          1

[514 rows x 5 columns]

In [1004]:
#### Again get the count of all the categories in 'Purchased' Column

df['Purchased'].value_counts()

Purchased
0    257
1    257
Name: count, dtype: int64

#### OBSERVATIONS:

1. After perfroming the upsampling on the minority class, the category 1 has been increased to 257. The total count of the category 0 = count of the category 1. So the dataset is a balanced.

#### Step 4: Perform the Feature Encoding


##### (a.)  Label Encoder

In [1005]:
df['Gender'].value_counts()

Gender
Female    276
Male      238
Name: count, dtype: int64

In [1006]:
d = df.copy()   #### used shallow copy

In [1007]:
d

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
364  15654456    Male   42           104000          1
20   15649487    Male   45            22000          1
331  15589715  Female   48           119000          1
373  15708791    Male   59           130000          1
223  15593715    Male   60           102000          1

[514 rows x 5 columns]

In [1008]:
#### perform the label encoding on the categorical columns

from sklearn.preprocessing import LabelEncoder

##### create an object for Label Encoder

lab = LabelEncoder()

df['Gender'] = lab.fit_transform(df['Gender'])

In [1009]:
df['Gender'].value_counts()

Gender
0    276
1    238
Name: count, dtype: int64

#### OBSERVATIONS:

1. Here Label Encoder has been applied on the Gender column. The 'Female' and 'Male' column in Gender has been converted into 0 and 1 value respectively.

In [1010]:
d

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
364  15654456    Male   42           104000          1
20   15649487    Male   45            22000          1
331  15589715  Female   48           119000          1
373  15708791    Male   59           130000          1
223  15593715    Male   60           102000          1

[514 rows x 5 columns]

##### (a.)  One Hot Encoder

In [1011]:
df_one = pd.get_dummies(df, columns= ['Gender'], drop_first=True)

In [1012]:
df_one

      User ID  Age  EstimatedSalary  Purchased  Gender_1
0    15624510   19            19000          0      True
1    15810944   35            20000          0      True
2    15668575   26            43000          0     False
3    15603246   27            57000          0     False
4    15804002   19            76000          0      True
..        ...  ...              ...        ...       ...
364  15654456   42           104000          1      True
20   15649487   45            22000          1      True
331  15589715   48           119000          1     False
373  15708791   59           130000          1      True
223  15593715   60           102000          1      True

[514 rows x 5 columns]

In [1013]:
#### perform map operation on it to map the categorical values into the numerical values

In [1014]:

df_one['Gender_1'] = df_one['Gender_1'].map({True:1, False :0})

In [1015]:
df_one = df_one.rename(columns={'Gender_1':'Gender'})

In [1016]:
df = df_one

In [1017]:
df

      User ID  Age  EstimatedSalary  Purchased  Gender
0    15624510   19            19000          0       1
1    15810944   35            20000          0       1
2    15668575   26            43000          0       0
3    15603246   27            57000          0       0
4    15804002   19            76000          0       1
..        ...  ...              ...        ...     ...
364  15654456   42           104000          1       1
20   15649487   45            22000          1       1
331  15589715   48           119000          1       0
373  15708791   59           130000          1       1
223  15593715   60           102000          1       1

[514 rows x 5 columns]

In [1018]:
#### Drop the unnecessary columns from the dataset

df.drop(columns = 'User ID', axis=1, inplace=True)

In [1019]:
df

     Age  EstimatedSalary  Purchased  Gender
0     19            19000          0       1
1     35            20000          0       1
2     26            43000          0       0
3     27            57000          0       0
4     19            76000          0       1
..   ...              ...        ...     ...
364   42           104000          1       1
20    45            22000          1       1
331   48           119000          1       0
373   59           130000          1       1
223   60           102000          1       1

[514 rows x 4 columns]

#### Step 5: Divide the dataset into independent and dependent features

In [1020]:
X = df.drop(columns = 'Purchased', axis=1)

In [1021]:
Y = df['Purchased']

In [1022]:
print(X)

     Age  EstimatedSalary  Gender
0     19            19000       1
1     35            20000       1
2     26            43000       0
3     27            57000       0
4     19            76000       1
..   ...              ...     ...
364   42           104000       1
20    45            22000       1
331   48           119000       0
373   59           130000       1
223   60           102000       1

[514 rows x 3 columns]

In [1023]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
364    1
20     1
331    1
373    1
223    1
Name: Purchased, Length: 514, dtype: int64

#### Step 6: Divide the independent and dependent features into the training and testing data

In [1024]:
from sklearn.model_selection  import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [1025]:
X_train

     Age  EstimatedSalary  Gender
280   59            88000       0
9     35            65000       0
33    28            44000       0
247   57           122000       0
111   37            71000       0
..   ...              ...     ...
383   49            28000       1
161   25            90000       1
172   26           118000       0
229   42            80000       0
54    27            58000       0

[411 rows x 3 columns]

In [1026]:
X_test

     Age  EstimatedSalary  Gender
107   27            89000       1
276   38            71000       1
127   26            32000       1
304   40            60000       0
234   38           112000       0
..   ...              ...     ...
343   47            51000       0
359   42            54000       1
382   44           139000       0
204   58           101000       0
21    47            49000       0

[103 rows x 3 columns]

In [1027]:
print("Shape of the input training data is:", X_train.shape)

print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (411, 3)
Shape of the input testing  data is: (103, 3)

In [1028]:
Y_train

280    1
9      0
33     0
247    1
111    0
      ..
383    1
161    0
172    0
229    1
54     0
Name: Purchased, Length: 411, dtype: int64

In [1029]:
Y_test

107    0
276    0
127    0
304    0
234    0
      ..
343    1
359    0
382    1
204    1
21     1
Name: Purchased, Length: 103, dtype: int64

In [1030]:
print("Shape of the output training data is:", Y_train.shape)

print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (411,)
Shape of the output testing  data is: (103,)

#### Step 7: Perform the Feature Scaling on the inputs

In [1031]:
from  sklearn.preprocessing   import  StandardScaler

#### create an object for Standard Scaler

sc = StandardScaler()

#### using the object for Standard Scaler, transform the inputs

X_train_scaled = sc.fit_transform(X_train)

X_test_scaled  = sc.transform(X_test)

In [1032]:
X_train_scaled

array([[ 1.78983691,  0.40224594, -0.88273483],
       [-0.38254543, -0.22449394, -0.88273483],
       [-1.01615694, -0.79673471, -0.88273483],
       ...,
       [-1.19718881,  1.21973274, -0.88273483],
       [ 0.25106608,  0.18424946, -0.88273483],
       [-1.10667287, -0.41524086, -0.88273483]], shape=(411, 3))

In [1033]:
X_test_scaled

array([[-1.10667287,  0.4294955 ,  1.13284303],
       [-0.11099764, -0.06099658,  1.13284303],
       [-1.19718881, -1.12372943,  1.13284303],
       [ 0.07003422, -0.36074174, -0.88273483],
       [-0.11099764,  1.05623538, -0.88273483],
       [ 0.79416167, -1.04198075, -0.88273483],
       [ 1.78983691, -1.20547811, -0.88273483],
       [-0.2920295 , -0.5242391 , -0.88273483],
       [-0.38254543, -0.36074174, -0.88273483],
       [-0.92564101,  0.26599814, -0.88273483],
       [ 1.88035284, -0.85123383,  1.13284303],
       [ 0.61312981, -1.23272767,  1.13284303],
       [ 1.24674132, -1.06923031, -0.88273483],
       [-0.20151357,  0.12975034, -0.88273483],
       [ 1.51828911, -0.36074174,  1.13284303],
       [-0.38254543, -0.55148866,  1.13284303],
       [-1.74028439,  0.23874858, -0.88273483],
       [ 0.16055015, -0.76948515,  1.13284303],
       [-0.38254543,  0.64749198, -0.88273483],
       [-1.74028439,  0.23874858, -0.88273483],
       [-1.55925253, -0.27899306, -0.88273483],
       [-0.38254543, -1.45072415,  1.13284303],
       [-0.38254543,  0.48399462,  1.13284303],
       [ 1.24674132,  0.8382389 , -0.88273483],
       [-0.65409322, -1.50522327,  1.13284303],
       [ 0.79416167, -0.87848339,  1.13284303],
       [ 0.07003422,  0.04800166, -0.88273483],
       [ 0.25106608,  0.94723714, -0.88273483],
       [ 0.25106608, -0.22449394,  1.13284303],
       [ 0.70364574, -1.17822855, -0.88273483],
       [-0.20151357, -0.55148866,  1.13284303],
       [ 0.79416167,  0.45674506,  1.13284303],
       [ 0.25106608,  0.04800166, -0.88273483],
       [-0.38254543,  0.48399462,  1.13284303],
       [ 0.07003422,  0.91998758,  1.13284303],
       [-0.47306136, -0.82398427,  1.13284303],
       [ 1.51828911, -0.36074174,  1.13284303],
       [ 0.61312981,  0.1569999 ,  1.13284303],
       [ 1.88035284,  0.94723714, -0.88273483],
       [ 0.79416167,  1.2469823 , -0.88273483],
       [ 0.61312981,  0.1569999 ,  1.13284303],
       [ 1.69932098, -0.71498603, -0.88273483],
       [ 0.8846776 , -1.23272767,  1.13284303],
       [ 0.61312981, -0.3879913 ,  1.13284303],
       [ 1.15622539,  0.45674506, -0.88273483],
       [ 1.15622539,  1.76472395, -0.88273483],
       [-0.56357729,  1.08348494, -0.88273483],
       [ 0.43209795,  1.79197351, -0.88273483],
       [-0.38254543, -0.93298251,  1.13284303],
       [ 0.79416167,  1.65572571, -0.88273483],
       [ 0.70364574, -1.36897547,  1.13284303],
       [ 0.61312981,  1.19248318,  1.13284303],
       [ 0.16055015, -0.03374702, -0.88273483],
       [-0.92564101,  0.18424946,  1.13284303],
       [ 1.88035284,  0.78373978,  1.13284303],
       [-0.38254543, -0.44249042, -0.88273483],
       [-0.74460915,  0.07525122,  1.13284303],
       [-0.38254543, -0.71498603, -0.88273483],
       [-0.20151357,  0.0207521 ,  1.13284303],
       [ 0.97519353, -1.45072415, -0.88273483],
       [ 0.16055015, -0.03374702,  1.13284303],
       [-0.38254543, -0.3879913 ,  1.13284303],
       [ 0.07003422, -0.03374702, -0.88273483],
       [-1.10667287,  0.45674506,  1.13284303],
       [ 1.78983691,  0.26599814, -0.88273483],
       [ 0.52261388,  0.1569999 ,  1.13284303],
       [ 0.8846776 ,  1.84647263, -0.88273483],
       [-0.83512508,  0.18424946,  1.13284303],
       [-1.19718881, -1.58697195,  1.13284303],
       [ 0.16055015,  0.1569999 ,  1.13284303],
       [ 0.70364574, -1.31447635,  1.13284303],
       [ 0.25106608, -0.2517435 ,  1.13284303],
       [-1.37822067, -1.47797371,  1.13284303],
       [ 1.15622539,  0.45674506, -0.88273483],
       [ 1.88035284, -0.85123383,  1.13284303],
       [ 0.79416167, -0.87848339,  1.13284303],
       [-0.38254543, -0.63323735,  1.13284303],
       [ 1.88035284, -1.06923031,  1.13284303],
       [ 0.79416167,  1.57397703, -0.88273483],
       [ 1.15622539,  1.76472395, -0.88273483],
       [ 0.79416167, -1.09647987,  1.13284303],
       [-1.28770474,  0.18424946,  1.13284303],
       [ 1.33725725, -1.28722679, -0.88273483],
       [-0.47306136, -0.03374702, -0.88273483],
       [ 0.16055015, -0.3879913 ,  1.13284303],
       [-0.56357729, -0.82398427,  1.13284303],
       [ 0.79416167,  1.84647263,  1.13284303],
       [-0.20151357,  0.10250078,  1.13284303],
       [ 1.88035284,  0.94723714, -0.88273483],
       [ 0.07003422, -0.44249042,  1.13284303],
       [ 1.69932098,  0.75649022, -0.88273483],
       [ 0.8846776 , -1.23272767,  1.13284303],
       [ 0.07003422, -0.06099658,  1.13284303],
       [-0.02048171,  0.10250078,  1.13284303],
       [ 1.69932098,  0.75649022, -0.88273483],
       [ 0.25106608,  2.06446911,  1.13284303],
       [-1.19718881,  0.34774682,  1.13284303],
       [-0.38254543, -1.25997723,  1.13284303],
       [ 0.70364574, -0.60598779, -0.88273483],
       [ 0.25106608, -0.5242391 ,  1.13284303],
       [ 0.43209795,  1.79197351, -0.88273483],
       [ 1.69932098,  0.75649022, -0.88273483],
       [ 0.70364574, -0.66048691, -0.88273483]])

#### Step 8: Train the Logistic Regression Model

In [1034]:
from  sklearn.linear_model  import LogisticRegression

#### create an object for Logistic Regression

log = LogisticRegression(max_iter=1000)

#### using the object of Logistic Regression, train the model

log.fit(X_train_scaled, Y_train)

LogisticRegression(max_iter=1000)

#### Step 9: Predict the Model

In [1035]:
Y_pred_log = log.predict(X_test_scaled)

In [1036]:
Y_pred_log

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1])

#### Step 10: Evalaute the Classification Metrics

In [1037]:
from  sklearn.metrics  import  accuracy_score, confusion_matrix, classification_report

#### Accuracy of the model

ac = accuracy_score(Y_test, Y_pred_log)*100.0

print("Accuracy score of the model is:", ac)

Accuracy score of the model is: 82.52427184466019

In [1038]:
#### Confusion Matrix of the model

cm = confusion_matrix(Y_test, Y_pred_log)

print("Confusion  Matrix of the model is:", cm)

Confusion  Matrix of the model is: [[37 15]
 [ 3 48]]

In [1039]:
#### Classification Report of the model

cr = classification_report(Y_test, Y_pred_log)

print("Classification  Report of the model is:", cr)

Classification  Report of the model is:               precision    recall  f1-score   support

           0       0.93      0.71      0.80        52
           1       0.76      0.94      0.84        51

    accuracy                           0.83       103
   macro avg       0.84      0.83      0.82       103
weighted avg       0.84      0.83      0.82       103

#### Step 11: Save and dump the model

In [1040]:
import joblib

joblib.dump(sc,"Standard_encoding.pickle")

['Standard_encoding.pickle']

In [1041]:
joblib.dump(log,"Logistic_encoding.pickle")

['Logistic_encoding.pickle']