### Simple Linear Regression

To implement a Simple Linear Regression for the Salary Dataset


#### Step 1: Import all the necessary libraries

In [337]:
import  numpy   as  np
import  pandas  as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

from    sklearn.model_selection     import  train_test_split
from    sklearn.preprocessing       import  StandardScaler
from    sklearn.linear_model        import  LinearRegression, Ridge, Lasso, ElasticNet
from    sklearn.metrics             import  mean_squared_error, mean_absolute_error, root_mean_squared_error, r2_score

### Step 2: Load the Dataset

In [338]:
df = pd.read_csv("Salary_Data.csv")

In [339]:
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

#### OBSERVATIONS:

1.  The above dataset contains the employees salary based on the Years of experience he worked.

#### Step 3: Perform the Data Exploration

In [340]:
print("Total length of the records in the dataset is:", len(df))

Total length of the records in the dataset is: 30

In [341]:
### shape of the dataset

print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (30, 2)

In [342]:
#### get the first five row of the dataset

df.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [343]:
### get the information about all the columns in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

#### Step 4: Perform Data Cleaning

In [344]:
#### Check for any NULL records in the dataset

df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL records in the dataframe.

In [345]:
### Check for any duplicate records

df[df.duplicated()]

Empty DataFrame
Columns: [YearsExperience, Salary]
Index: []

### OBSERVATIONS:

1.  There are no duplicate records in the dataframe.

#### Step 5: Divide the dataset into independent and dependent features

In [346]:
#### independent features

X = df[['YearsExperience']]

print(X)

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [347]:
#### dependent features

Y = df['Salary']

print(Y)

0      39343.0
1      46205.0
2      37731.0
3      43525.0
4      39891.0
5      56642.0
6      60150.0
7      54445.0
8      64445.0
9      57189.0
10     63218.0
11     55794.0
12     56957.0
13     57081.0
14     61111.0
15     67938.0
16     66029.0
17     83088.0
18     81363.0
19     93940.0
20     91738.0
21     98273.0
22    101302.0
23    113812.0
24    109431.0
25    105582.0
26    116969.0
27    112635.0
28    122391.0
29    121872.0
Name: Salary, dtype: float64

#### Step 6: Divide the independent and dependent features into training and testing data

In [348]:
from    sklearn.model_selection import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [349]:
X_train

    YearsExperience
28             10.3
24              8.7
12              4.0
0               1.1
4               2.2
16              5.1
5               2.9
13              4.1
11              4.0
22              7.9
1               1.3
2               1.5
25              9.0
3               2.0
21              7.1
26              9.5
18              5.9
29             10.5
20              6.8
7               3.2
10              3.9
14              4.5
19              6.0
6               3.0

In [350]:
X_test

    YearsExperience
27              9.6
15              4.9
23              8.2
17              5.3
8               3.2
9               3.7

In [351]:
print("Shape of the input training data is:", X_train.shape)

print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (24, 1)
Shape of the input testing  data is: (6, 1)

In [352]:
Y_train

28    122391.0
24    109431.0
12     56957.0
0      39343.0
4      39891.0
16     66029.0
5      56642.0
13     57081.0
11     55794.0
22    101302.0
1      46205.0
2      37731.0
25    105582.0
3      43525.0
21     98273.0
26    116969.0
18     81363.0
29    121872.0
20     91738.0
7      54445.0
10     63218.0
14     61111.0
19     93940.0
6      60150.0
Name: Salary, dtype: float64

In [353]:
Y_test

27    112635.0
15     67938.0
23    113812.0
17     83088.0
8      64445.0
9      57189.0
Name: Salary, dtype: float64

In [354]:
print("Shape of the output training data is:", Y_train.shape)

print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (24,)
Shape of the output testing  data is: (6,)

### Step 6: Train the Model using Linear Regression , Ridge, Lasso, Elastic Net

### (a.) Linear Regression

In [355]:
from    sklearn.linear_model    import LinearRegression, Ridge, Lasso, ElasticNet

#### create an object for LinearRegression

lin = LinearRegression()

### using the object train the model

lin.fit(X_train, Y_train)

#### using the object, predict the model

Y_pred_lin = lin.predict(X_test)

print(Y_pred_lin)


#### get the score of the model

r2 = r2_score(Y_test, Y_pred_lin)

print("R2 Score of the model is:", r2)

[115790.21011287  71498.27809463 102596.86866063  75267.80422384
  55477.79204548  60189.69970699]
R2 Score of the model is: 0.9024461774180497

#### OBSERVATIONS:

1.  As the R2 Score of the model is 0.9. It is very high. So the model is working perfectly fine.

### (b.)  Ridge Regression

In [356]:
from    sklearn.linear_model    import LinearRegression, Ridge, Lasso, ElasticNet

#### create an object for Ridge Regression

ridge = Ridge(alpha=1.0)

### using the object train the model

ridge.fit(X_train, Y_train)

#### using the object, predict the model

Y_pred_ridge  = ridge.predict(X_test)

print(Y_pred_ridge)

#### get the score of the model

ridge_r2 = r2_score(Y_test, Y_pred_ridge)

print("R2 Score of the model is:", ridge_r2)

[115582.53212304  71511.80952173 102455.08283754  75262.50931758
  55571.33538934  60259.71013416]
R2 Score of the model is: 0.9021627846740267

#### OBSERVATIONS:

1.  As the R2 Score of the model using Ridge Regression is 0.9. It is very high. So the model is working perfectly fine.

2.  Ridge Regression is used to prevent the overfitting.

### (c.)  Lasso Regression

In [357]:
from    sklearn.linear_model    import LinearRegression, Ridge, Lasso, ElasticNet

#### create an object for Lasso Regression

lasso = Lasso(alpha=0.1)

### using the object train the model

lasso.fit(X_train, Y_train)

#### using the object, predict the model

Y_pred_lasso  = lasso.predict(X_test)

print(Y_pred_lasso)

#### get the score of the model

lasso_r2 = r2_score(Y_test, Y_pred_lasso)

print("R2 Score of the model is:", lasso_r2)

[115790.15695723  71498.28155803 102596.83237023  75267.8028686
  55477.8159881   60189.71762632]
R2 Score of the model is: 0.9024461113200314

#### OBSERVATIONS:

1.  As the R2 Score of the model using Lasso Regression is 0.9. It is very high. So the model is working perfectly fine.

2.  Lasso Regression is used to perform the feature selection.

### (d.)  Elastic Net Regression

In [358]:
from    sklearn.linear_model    import LinearRegression, Ridge, Lasso, ElasticNet

#### create an object for Lasso Regression

elasticnet = ElasticNet(alpha=1.0, l1_ratio = 0.5)

### using the object train the model

elasticnet.fit(X_train, Y_train)

#### using the object, predict the model

Y_pred_elasticnet  = elasticnet.predict(X_test)

print(Y_pred_elasticnet)

#### get the score of the model

lasso_elasticnet = r2_score(Y_test, Y_pred_elasticnet)

print("R2 Score of the model is:", lasso_elasticnet)

[113427.60616874  71652.21546209 100983.87276676  75207.56786266
  56541.96775969  60986.1582604 ]
R2 Score of the model is: 0.8962527621642432

#### OBSERVATIONS:

1.  As the R2 Score of the model using Elastic Net Regression is 0.8962. It is very high. So the model is working perfectly fine.

2.  Elastic Net Regression is used to perform the feature selection as well as remove the overfitting.

3.  The r2 score for Lasso > r2 score for ridge > r2 score for elastic net.

### Step 7: Perform Cross Validation

In [359]:
from sklearn.model_selection import cross_val_score

### Train the model using Ridge Regression

model = Ridge(alpha=1.0)
scores = cross_val_score(model,X,Y,cv = 5, scoring='r2')

print("Cross Validation score is:", scores)

print("Average scores for the cross validation is:", np.mean(scores))

Cross Validation score is: [ 0.38581697 -1.22593659  0.2441607   0.28343226  0.22359091]
Average scores for the cross validation is: -0.01778715230694672