#### Build a machine learning model and predict whether the particular customer will leave or not using Cross Validation techniques


##### Step 1: Import all the necessary libraries

In [1002]:
import      numpy                   as      np
import      pandas                  as      pd
import      matplotlib.pyplot       as      plt
import      seaborn                 as      sns
import      joblib

from        sklearn.model_selection   import   train_test_split, KFold, cross_val_score
from        sklearn.preprocessing     import   StandardScaler
from        sklearn.linear_model      import   LogisticRegression
from        sklearn.metrics           import   accuracy_score, confusion_matrix, classification_report

#### Step 2: Load the Dataset

In [1003]:
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [1004]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

#### OBSERVATIONS:

1. The above dataset explains about all the details of the customer who will leave the bank or not.

2. There are a total of 7043 records.

3. The independent features are from CustomerID......totalcharges. These are the inputs.

4. The dependent feature is the Churn. The output is in the form of Yes/No. These are the outputs.

#### Step 3: Perform the Data Exploration

In [1005]:
#### Get the total length of the dataset

print("Length of the dataset is:", len(df))

Length of the dataset is: 7043

In [1006]:
#### Get the shape of the dataset

print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (7043, 21)

In [1007]:
#### Get the columns used in the dataset

print("Columns used in the dataset is:", df.columns)

Columns used in the dataset is: Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [1008]:
#### Get the information about the columns used in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [1009]:
#### Get the descriptive statistical summary about the data in the dataset

df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

#### Step 4: Perform the Data Cleaning

In [1010]:
#### To check for any NULL records in the dataset

df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL records in the dataset.

In [1011]:
#### To check for any duplicate records in the dataset

df[df.duplicated()]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

#### OBSERVATIONS:

1.  There are no duplicate records in the dataset.

In [1012]:
#### Drop the unnecessary columns from the dataset

df.drop(columns='customerID',axis=1,inplace=True)

In [1013]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [1014]:
#### Encode all the categorical columns

from sklearn.preprocessing  import LabelEncoder

#### create an object for Label Encoder

label = LabelEncoder()


#### using the object for label encoder, train the model

for col in df.columns:
    #### To check for all the categorical columns
    if(df[col].dtype == 'object'):
        df[col] = label.fit_transform(df[col])

In [1015]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407,0

#### OBSERVATIONS:

1.  All the categorical columns have been encoded using Label Encoding.

#### Step 5: Divide the dataset into independent and dependent features

In [1016]:
#### independent features

X = df.drop(columns = 'Churn',axis=1)

In [1017]:
#### dependent features

In [1018]:
Y = df['Churn']

In [1019]:
print(X)

      gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0          0              0        1           0       1             0
1          1              0        0           0      34             1
2          1              0        0           0       2             1
3          1              0        0           0      45             0
4          0              0        0           0       2             1
...      ...            ...      ...         ...     ...           ...
7038       1              0        1           1      24             1
7039       0              0        1           1      72             1
7040       0              0        1           1      11             0
7041       1              1        1           0       4             1
7042       1              0        0           0      66             1

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0                 1                0               0             2
1                 0                0               2             0
2                 0                0               2             2
3                 1                0               2             0
4                 0                1               0             0
...             ...              ...             ...           ...
7038              2                0               2             0
7039              2                1               0             2
7040              1                0               2             0
7041              2                1               0             0
7042              0                1               2             0

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    0            0            0                0         0
1                    2            0            0                0         1
2                    0            0            0                0         0
3                    2            2            0                0         1
4                    0            0            0                0         0
...                ...          ...          ...              ...       ...
7038                 2            2            2                2         1
7039                 2            0            2                2         1
7040                 0            0            0                0         0
7041                 0            0            0                0         0
7042                 2            2            2                2         2

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges
0                    1              2           29.85          2505
1                    0              3           56.95          1466
2                    1              3           53.85           157
3                    0              0           42.30          1400
4                    1              2           70.70           925
...                ...            ...             ...           ...
7038                 1              3           84.80          1597
7039                 1              1          103.20          5698
7040                 1              2           29.60          2994
7041                 1              3           74.40          2660
7042                 1              0          105.65          5407

[7043 rows x 19 columns]

In [1020]:
X.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [1021]:
print(Y)

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

#### OBSERVATIONS:

1.  The dataset is divided into the independent and dependent variables.

    (a.)   Independent variables --------->  Gender........ TotalCharges

    (b.)   Dependent   variables --------->  Churn

#### Step 6:  Divide the independent and dependent variables into the training and testing data

In [1022]:
from  sklearn.model_selection  import train_test_split, KFold, cross_val_score

#### Divide the dataset into the training and testing data

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [1023]:
X_train

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
3738,1,0,0,0,35,0,1,0,0,0,2,0,2,2,0,0,2,49.20,1201
3151,1,0,1,1,15,1,0,1,2,0,0,0,0,0,0,0,3,75.10,288
4860,1,0,1,1,13,0,1,0,2,2,0,2,0,0,2,0,3,40.55,4847
3867,0,0,1,0,26,1,0,0,0,2,2,0,2,2,2,1,1,73.50,1505
3810,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,2,44.55,3743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6303,0,0,1,0,71,1,2,1,0,2,2,2,2,2,2,0,2,109.25,5872
6227,1,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0,0,46.05,6019
4673,0,1,0,0,25,1,2,1,2,2,0,0,2,2,0,1,3,102.80,2316
2710,0,0,1,0,24,1,0,2,1,1,1,1,1,1,1,0,1,20.40,4072
5639,1,0,0,0,6,1,0,2,1,1,1,1,1,1,0,0,3,20.65,175

In [1024]:
X_test

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
437,1,0,1,1,72,1,2,1,2,2,2,2,2,2,2,1,1,114.05,6196
2280,0,1,0,0,8,1,2,1,0,0,0,2,2,2,0,1,1,100.15,6340
2235,0,0,1,1,41,1,2,0,2,2,2,0,2,0,1,1,1,78.35,2796
4460,1,0,1,0,18,1,0,1,0,0,2,2,0,0,0,0,2,78.20,862
3761,0,0,1,0,72,1,2,0,2,2,2,0,2,2,2,1,1,82.65,4855
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5143,0,0,1,1,49,1,0,0,2,2,2,2,2,2,1,1,3,87.20,3692
4439,1,0,1,1,28,1,0,2,1,1,1,1,1,1,2,1,1,20.30,4114
3857,1,0,0,0,5,1,0,2,1,1,1,1,1,1,0,0,0,20.65,6393
4758,0,0,0,0,56,1,0,2,1,1,1,1,1,1,2,0,0,19.70,100
5613,0,0,1,1,72,1,2,0,2,2,2,2,0,0,2,1,0,70.45,4338

In [1025]:
print("Shape of the input training data is:",X_train.shape)
print("Shape of the input testing  data is:",X_test.shape)

Shape of the input training data is: (5634, 19)
Shape of the input testing  data is: (1409, 19)

In [1026]:
Y_train

3738    0
3151    0
4860    0
3867    0
3810    0
       ..
6303    0
6227    1
4673    1
2710    0
5639    0
Name: Churn, Length: 5634, dtype: int64

In [1027]:
Y_test

437     0
2280    0
2235    0
4460    0
3761    0
       ..
5143    0
4439    0
3857    0
4758    0
5613    0
Name: Churn, Length: 1409, dtype: int64

In [1028]:
print("Shape of the output training data is:",Y_train.shape)
print("Shape of the output testing  data is:",Y_test.shape)

Shape of the output training data is: (5634,)
Shape of the output testing  data is: (1409,)

### OBSERVATIONS:

1.  The dataset is divided into the training and testing data.

    (a.)  The training data contains 80 % of the records.

    (b.)  The testing  data contains 20 % of the records.

#### Step 7: Perform Feature Scaling on the inputs

In [1029]:
from sklearn.preprocessing  import  StandardScaler

#### Craete an object for Standard Scaler

sc = StandardScaler()

#### Using the object for Standard Scaler, transform the inputs

X_train_scaled = sc.fit_transform(X_train)

X_test_scaled  = sc.transform(X_test)

In [1030]:
X_train_scaled

array([[ 0.99433624, -0.44177295, -0.96923413, ...,  0.40093316,
        -0.52197565, -1.10327574],
       [ 0.99433624, -0.44177295,  1.03174245, ...,  1.33627784,
         0.33747781, -1.58627808],
       [ 0.99433624, -0.44177295,  1.03174245, ...,  1.33627784,
        -0.80901319,  0.82555946],
       ...,
       [-1.00569602,  2.2636062 , -0.96923413, ...,  1.33627784,
         1.25666162, -0.51340979],
       [-1.00569602, -0.44177295,  1.03174245, ..., -0.53441153,
        -1.47766135,  0.41556295],
       [ 0.99433624, -0.44177295, -0.96923413, ...,  1.33627784,
        -1.46936546, -1.64605822]], shape=(5634, 19))

In [1031]:
X_test_scaled

array([[ 0.99433624, -0.44177295,  1.03174245, ..., -0.53441153,
         1.62997635,  1.5392179 ],
       [-1.00569602,  2.2636062 , -0.96923413, ..., -0.53441153,
         1.16872526,  1.61539789],
       [-1.00569602, -0.44177295,  1.03174245, ..., -0.53441153,
         0.44532428, -0.25947647],
       ...,
       [ 0.99433624, -0.44177295, -0.96923413, ..., -1.46975621,
        -1.46936546,  1.64343637],
       [-1.00569602, -0.44177295, -0.96923413, ..., -1.46975621,
        -1.50088982, -1.6857353 ],
       [-1.00569602, -0.44177295,  1.03174245, ..., -1.46975621,
         0.18317439,  0.55628433]], shape=(1409, 19))

#### OBSERVATIONS:

1.  All the inputs have been scaled in one range.

#### Step 8: Train the LogisticRegressionModel and also apply cross validation on it

In [1032]:
from  sklearn.linear_model  import LogisticRegression

#### create an object for Logistic Regression

log = LogisticRegression(max_iter=1000)

#### Apply cross validation on the logistic regression model to improve its accuracy

### use kfold to divide the dataset

kfold = KFold(n_splits=5, shuffle=True, random_state=42)

#### then compute the cross validation score

cvscore = cross_val_score(log, X_train_scaled, Y_train, cv = kfold, scoring= 'accuracy')


print("Cross Validation Score of the model is:", cvscore)

print("Mean Accuracy is:", np.mean(cvscore))

Cross Validation Score of the model is: [0.79591837 0.81632653 0.79591837 0.81011535 0.79040853]
Mean Accuracy is: 0.8017374283098058

In [1033]:
#### Train the Model

log.fit(X_train_scaled, Y_train)

LogisticRegression(max_iter=1000)

#### OBSERVATIONS:

1.  The dataset is divided into the K number of folds.

2.  Each fold has a training and validation accuracy.

3.  Each fold computes a accuracy .

4.  Then the mean or the average of all the accuracies is computed

5.  The cross validation is performed so as to:-----

    (a.)  To reduce the overfitting.

    (b.)  To improve the performance of the model.

    (c.)  To efficiently use the  datasets.


6.  The Logistic Regression model is trained with the help of the training data

#### Step 9: Predict the Model

In [1034]:
Y_pred = log.predict(X_test_scaled)

In [1035]:
Y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

#### Step 10: Evaluate the Classification Metrics

In [1036]:
from  sklearn.metrics  import accuracy_score, confusion_matrix, classification_report


print('==================Accuracy Score =====================================')

ac = accuracy_score(Y_test, Y_pred)

print("Accuracy score of the model is:", (ac * 100.0))

==================Accuracy Score =====================================
Accuracy score of the model is: 79.63094393186657

In [1037]:
print('==================Confusion Matrix=====================================')

cm = confusion_matrix(Y_test, Y_pred)

print("Confusion Matrix of the model is:", (cm))

==================Confusion Matrix=====================================
Confusion Matrix of the model is: [[925 110]
 [177 197]]

In [1038]:
print("===================Classification Report================================")

cr = classification_report(Y_test, Y_pred)

print("Classification Report of the Model is:", cr)

===================Classification Report================================
Classification Report of the Model is:               precision    recall  f1-score   support

           0       0.84      0.89      0.87      1035
           1       0.64      0.53      0.58       374

    accuracy                           0.80      1409
   macro avg       0.74      0.71      0.72      1409
weighted avg       0.79      0.80      0.79      1409

#### OBSERVATIONS:

1.  As the accuracy of the model is 79.6 which is very high. So the model is working very fine.

#### Step 11: Save and dump the model

In [1039]:
import joblib

joblib.dump(sc,"Standard_Val.pickle")

['Standard_Val.pickle']

In [1040]:
joblib.dump(log,"Logistic_Val.pickle")

['Logistic_Val.pickle']