### Data Manipulation:

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

In [613]:
import pandas as pd

In [614]:
df = pd.read_csv('data.csv')

In [615]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

### OBSERVATIONS:

1.  The above dataset depicts about the details of all the products, its sales amount, category, region and in which data, the product it was purchased.

In [616]:
### Display the first five rows of the dataset

df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [617]:
### Display the last five rows of the dataset

df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [618]:
### get all the columns used in the dataset

df.columns

Index(['Date', 'Category', 'Value', 'Product', 'Sales', 'Region'], dtype='str')

In [619]:
### get the information about all the columns used in the dataset

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     str
 1   Category  50 non-null     str
 2   Value     47 non-null     float64
 3   Product   50 non-null     str
 4   Sales     46 non-null     float64
 5   Region    50 non-null     str
dtypes: float64(2), str(4)
memory usage: 2.5 KB

In [620]:
### get the descriptive statistics about the columns used in the dataset

df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [621]:
### get the missing values used in the dataset

df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

### OBSERVATIONS:

1. There are some NULL Values in the Value and Sales columns in the dataset.

In [622]:
df[df['Value'].isnull()]

          Date Category  Value   Product  Sales Region
15  2023-01-16        C    NaN  Product1  895.0  North
17  2023-01-18        C    NaN  Product1  108.0   West
28  2023-01-29        B    NaN  Product3  617.0  North

In [623]:
### Replace all the null value of 'Values' with the mean value of it

df['Value'] = df['Value'].fillna(df['Value'].mean())

In [624]:
df[df['Value'].isnull()]

Empty DataFrame
Columns: [Date, Category, Value, Product, Sales, Region]
Index: []

### OBSERVATIONS:

1. Here all the NULL Values of the 'Value' column has been replace with the mean value of it

In [625]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       4
Region      0
dtype: int64

In [626]:
df[df['Sales'].isnull()]

          Date Category  Value   Product  Sales Region
11  2023-01-12        B   60.0  Product2    NaN   West
33  2023-02-03        C   27.0  Product3    NaN   East
35  2023-02-05        B   60.0  Product2    NaN   West
37  2023-02-07        C    2.0  Product1    NaN  North

In [627]:
### Replace all the null value of 'Sales' with the mean value of it

df['Sales'] = df['Sales'].fillna(df['Sales'].mean())

In [628]:
df[df['Sales'].isnull()]

Empty DataFrame
Columns: [Date, Category, Value, Product, Sales, Region]
Index: []

### OBSERVATIONS:

1. Here all the NULL Values of the 'Sales' column has been replace with the mean value of it

In [629]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [630]:
## Renaming Columns

df.rename(columns={'Date':'Sales Date'},inplace=True)


df.head()

   Sales Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

### OBSERVATIONS:

1. After renaming, the column 'Date' has been renamed to 'Sales Date'.

In [631]:
## change datatypes
df['Value_new']=df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

   Sales Date Category  Value   Product  Sales Region  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         28
1  2023-01-02        B   39.0  Product3  110.0  North         39
2  2023-01-03        C   32.0  Product2  398.0   East         32
3  2023-01-04        B    8.0  Product1  522.0   East          8
4  2023-01-05        B   26.0  Product3  869.0  North         26

In [632]:
### Square the value present in 'Value' and store in a new column 'Value_news'

df['Value_news'] = df['Value'].apply(lambda x:x**2)

df.head()

   Sales Date Category  Value   Product  Sales Region  Value_new  Value_news
0  2023-01-01        A   28.0  Product1  754.0   East         28       784.0
1  2023-01-02        B   39.0  Product3  110.0  North         39      1521.0
2  2023-01-03        C   32.0  Product2  398.0   East         32      1024.0
3  2023-01-04        B    8.0  Product1  522.0   East          8        64.0
4  2023-01-05        B   26.0  Product3  869.0  North         26       676.0

### OBSERVATIONS:

1. We have made the new column 'Value_news' that stores the square of the 'Value' column.

In [633]:
### Find out the mean value of the sales in a product wise manner

grouped_mean = df.groupby('Product')['Sales'].mean()

In [634]:
print(grouped_mean)

Product
Product1    573.758152
Product2    565.884058
Product3    536.217391
Name: Sales, dtype: float64

### OBSERVATIONS:

1.  Here we have obtained the mean value of the sales per product.

In [635]:
### Find out the mean value of the sales in a product wise manner, region wise

grouped_mean_sales_data = df.groupby(['Product','Region'])['Sales'].mean()

In [636]:
print(grouped_mean_sales_data)

Product   Region
Product1  East      600.714286
          North     764.710145
          South     673.000000
          West      333.750000
Product2  East      428.000000
          North     421.500000
          South     746.666667
          West      568.657609
Product3  East      628.282609
          North     571.333333
          South     524.000000
          West      445.833333
Name: Sales, dtype: float64

### OBSERVATIONS:

1.  Here we have obtained the mean values of the sales per product per region.

In [637]:
## aggregate multiple functions
groudped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
groudped_agg

             mean          sum  count
Region
East    42.307692   550.000000     13
North   40.226306   442.489362     11
South   62.000000   496.000000      8
West    61.041371  1098.744681     18

In [638]:
### Merging and joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [639]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [640]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [641]:
### perform the inner merge on the data frames

pd.merge(df1,df2,on='Key',how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [642]:
### perform the left merge on the data frames

pd.merge(df1,df2,on='Key',how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [643]:
### perform the right merge on the data frames

pd.merge(df1,df2,on='Key',how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [644]:
### perform the outer merge on the data frames

pd.merge(df1,df2,on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

### OBSERVATIONS:

1.   Here we have performed the left join, right join , inner join and the outer join on the two dataframes to get the output.