#### Perform the Faeture Scaling technique on the diabetes dataset and check whether the performance of the model increases or not


##### Step 1:   Import  all the  necessary  libraries

In [612]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

from    sklearn.model_selection    import  train_test_split
from    sklearn.preprocessing      import  StandardScaler, MinMaxScaler, Normalizer
from    sklearn.linear_model       import  LogisticRegression
from    sklearn.metrics            import  accuracy_score, confusion_matrix, classification_report

#### Step 2: Load the Dataset

In [613]:
#### define the url

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"

#### define all the column names


columns = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness",
           "Insulin", "BMI", "DPF", "Age", "Outcome"]


##### define the dataset from the url and the columns

df = pd.read_csv(url, names = columns)

print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI    DPF  \
0              6      148             72             35        0  33.6  0.627
1              1       85             66             29        0  26.6  0.351
2              8      183             64              0        0  23.3  0.672
3              1       89             66             23       94  28.1  0.167
4              0      137             40             35      168  43.1  2.288
..           ...      ...            ...            ...      ...   ...    ...
763           10      101             76             48      180  32.9  0.171
764            2      122             70             27        0  36.8  0.340
765            5      121             72             23      112  26.2  0.245
766            1      126             60              0        0  30.1  0.349
767            1       93             70             31        0  30.4  0.315

     Age  Outcome
0     50        1
1     31        0
2     32        1
3     21        0
4     33        1
..   ...      ...
763   63        0
764   27        0
765   30        0
766   47        1
767   23        0

[768 rows x 9 columns]

#### OBSERVATIONS:

1.  The above dataset explains about the diabetic situation for each and every patient.

#### Step 3: Perform the Data Exploration

In [614]:
#### get the first five rows of the dataset

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

##### Step 4: Perform the Data Cleaning

In [615]:
#### Check whether there are any NULL Values in the dataset

df.isnull().sum()

Pregnancies      0
Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
DPF              0
Age              0
Outcome          0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL records in the dataset.

In [616]:
#### To check for the duplicate records in the dataset

df[df.duplicated()]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DPF, Age, Outcome]
Index: []

#### OBSERVATIONS:

1.  There are no duplicate records in the dataset.

In [617]:
#### Replace all the zeros value in the column with the median value

col = ["Pregnancies", "Glucose" , "BloodPressure" , "SkinThickness" , "Insulin", "BMI", "DPF", "Age"]

for x in  col:
    #### Replace all the zeros with the median value of it
    df[x] = df[x].replace(0, df[x].median())


df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age,Outcome
0,6,148,72,35,30.5,33.6,0.627,50,1
1,1,85,66,29,30.5,26.6,0.351,31,0
2,8,183,64,23,30.5,23.3,0.672,32,1
3,1,89,66,23,94.0,28.1,0.167,21,0
4,3,137,40,35,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180.0,32.9,0.171,63,0
764,2,122,70,27,30.5,36.8,0.340,27,0
765,5,121,72,23,112.0,26.2,0.245,30,0
766,1,126,60,23,30.5,30.1,0.349,47,1
767,1,93,70,31,30.5,30.4,0.315,23,0

#### OBSERVATIONS:

1.  All the zeros in every column has been replaced with the median value of that column.

#### Step 5: Divide the dataset into independent and dependent variables

In [618]:
##### independent variables

X = df.drop(columns = 'Outcome', axis = 1)

In [619]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age
0,6,148,72,35,30.5,33.6,0.627,50
1,1,85,66,29,30.5,26.6,0.351,31
2,8,183,64,23,30.5,23.3,0.672,32
3,1,89,66,23,94.0,28.1,0.167,21
4,3,137,40,35,168.0,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180.0,32.9,0.171,63
764,2,122,70,27,30.5,36.8,0.340,27
765,5,121,72,23,112.0,26.2,0.245,30
766,1,126,60,23,30.5,30.1,0.349,47
767,1,93,70,31,30.5,30.4,0.315,23

In [620]:
#### dependent variables

Y = df['Outcome']

In [621]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

#### OBSERVATIONS:

1.  The dataset is divided into the independent and dependent variables

    (a.)  The independent variables are from Pregnancies ....... Age

    (b.)  The dependent   variable is the Outcome which is the output.

#### Step 6: Divide the independent and dependent variables into the training and testing data

In [622]:
from  sklearn.model_selection  import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [623]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age
353,1,90,62,12,43.0,27.2,0.580,24
711,5,126,78,27,22.0,29.6,0.439,40
373,2,105,58,40,94.0,34.9,0.225,25
46,1,146,56,23,30.5,29.7,0.564,29
682,3,95,64,39,105.0,44.6,0.366,22
...,...,...,...,...,...,...,...,...
451,2,134,70,23,30.5,28.9,0.542,23
113,4,76,62,23,30.5,34.0,0.391,25
556,1,97,70,40,30.5,38.1,0.218,30
667,10,111,70,27,30.5,27.5,0.141,40
107,4,144,58,28,140.0,29.5,0.287,37

In [624]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DPF,Age
44,7,159,64,23,30.5,27.4,0.294,40
672,10,68,106,23,49.0,35.5,0.285,47
700,2,122,76,27,200.0,35.9,0.483,26
630,7,114,64,23,30.5,27.4,0.732,34
81,2,74,72,23,30.5,32.0,0.102,22
...,...,...,...,...,...,...,...,...
32,3,88,58,11,54.0,24.8,0.267,22
637,2,94,76,18,66.0,31.6,0.649,23
593,2,82,52,22,115.0,28.5,1.699,25
425,4,184,78,39,277.0,37.0,0.264,31
273,1,71,78,50,45.0,33.2,0.422,21

In [625]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (614, 8)
Shape of the input testing  data is: (154, 8)

In [626]:
Y_train

353    0
711    0
373    0
46     0
682    0
      ..
451    1
113    0
556    0
667    1
107    0
Name: Outcome, Length: 614, dtype: int64

In [627]:
Y_test

44     0
672    0
700    0
630    1
81     0
      ..
32     0
637    0
593    0
425    1
273    0
Name: Outcome, Length: 154, dtype: int64

In [628]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (614,)
Shape of the output testing  data is: (154,)

#### OBSERVATIONS:

1.  The dataset is divided into independent and dependent features


    (a.)  Independent feature contains 80 % of the data

    (b.)  Dependent   feature contains 20 % of the data

#### Step 7: Perform without Feature Scaling

In [629]:
from  sklearn.linear_model  import LogisticRegression

#### Create an object for Logistic Regression

log = LogisticRegression(max_iter=1000)


#### using the object of Logistic Regression, train the model

log.fit(X_train, Y_train)

#### predict the model

Y_pred = log.predict(X_test)

print(Y_pred)

#### Perform the Classification metrics on the inputs

from  sklearn.metrics  import  accuracy_score, confusion_matrix, classification_report

ac = accuracy_score(Y_test, Y_pred)*100.0

print("Accuracy score of the model is:", ac)


cm = confusion_matrix(Y_test, Y_pred)


print("Confusion Matrix of the model is:", cm)

cr = classification_report(Y_test, Y_pred)

print(cr)

[1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0]
Accuracy score of the model is: 70.77922077922078
Confusion Matrix of the model is: [[82 18]
 [27 27]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154

#### OBSERVATIONS:

1.  The overall accuracy of the model without feature scaling is 70.77 which is fine.

#### Step 8: Perform the Feature scaling on the inputs

#### (a.)   StandardScaler

In [630]:
from  sklearn.linear_model  import LogisticRegression

#### Create an object for Standard Scaler

sc = StandardScaler()

X_train_scaledsc = sc.fit_transform(X_train)

X_test_scaledsc  = sc.transform(X_test)

#### Create an object for Logistic Regression

logsc = LogisticRegression(max_iter=1000)


#### using the object of Logistic Regression, train the model

logsc.fit(X_train_scaledsc, Y_train)

#### predict the model

Y_pred_sc = logsc.predict(X_test_scaledsc)

print(Y_pred_sc)

#### Perform the Classification metrics on the inputs

from  sklearn.metrics  import  accuracy_score, confusion_matrix, classification_report

ac_sc = accuracy_score(Y_test, Y_pred_sc)*100.0

print("Accuracy score of the model is:", ac_sc)


cm_sc = confusion_matrix(Y_test, Y_pred_sc)


print("Confusion Matrix of the model is:", cm_sc)

cr_sc = classification_report(Y_test, Y_pred_sc)

print(cr_sc)

[1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0]
Accuracy score of the model is: 70.77922077922078
Confusion Matrix of the model is: [[82 18]
 [27 27]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78       100
           1       0.60      0.50      0.55        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154

#### (b.)  MinMaxScaler

In [631]:
from  sklearn.linear_model  import LogisticRegression

#### Create an object for Standard Scaler

minmax = MinMaxScaler()

X_train_scaledminmax = minmax.fit_transform(X_train)

X_test_scaledminmax  = minmax.transform(X_test)

#### Create an object for Logistic Regression

logminmax = LogisticRegression(max_iter=1000)


#### using the object of Logistic Regression, train the model

logminmax.fit(X_train_scaledminmax, Y_train)

#### predict the model

Y_pred_minmax = logminmax.predict(X_test_scaledminmax)

print(Y_pred_minmax)

#### Perform the Classification metrics on the inputs

from  sklearn.metrics  import  accuracy_score, confusion_matrix, classification_report

ac_minmax = accuracy_score(Y_test, Y_pred_minmax)*100.0

print("Accuracy score of the model is:", ac_minmax)


cm_minmax = confusion_matrix(Y_test, Y_pred_minmax)


print("Confusion Matrix of the model is:", cm_minmax)

cr_minmax = classification_report(Y_test, Y_pred_minmax)

print(cr_minmax)

[1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0]
Accuracy score of the model is: 71.42857142857143
Confusion Matrix of the model is: [[84 16]
 [28 26]]
              precision    recall  f1-score   support

           0       0.75      0.84      0.79       100
           1       0.62      0.48      0.54        54

    accuracy                           0.71       154
   macro avg       0.68      0.66      0.67       154
weighted avg       0.70      0.71      0.70       154

#### (c.) Normalizer

In [632]:
from  sklearn.preprocessing  import StandardScaler, MinMaxScaler, Normalizer

#### Perform the Standard Scaler technique

norm = Normalizer()

X_train_norm = norm.fit_transform(X_train)

X_test_norm  = norm.transform(X_test)


#### Train the model

from  sklearn.linear_model  import LogisticRegression

#### Create an object for Logistic Regression

log_norm = LogisticRegression(max_iter=1000)

#### using the object of Logistic Regression, train the model

log_norm.fit(X_train_norm, Y_train)


#### using the object of logistic regression, predict the model

Y_pred_norm = log_norm.predict(X_test_norm)

print(Y_pred_norm)

##### Evaluate the Classification Metrics

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

ac_norm = accuracy_score(Y_test, Y_pred_norm)*100.0

print("Accuracy score of the model is", ac_norm)


cm_norm = confusion_matrix(Y_test, Y_pred_norm)

print("Confusion Matrix of the model is", cm_norm)


cr_norm = classification_report(Y_test, Y_pred_norm)

print("Classification Report of the model is", cr_norm)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0]

Accuracy score of the model is 65.5844155844156
Confusion Matrix of the model is [[97  3]
 [50  4]]
Classification Report of the model is               precision    recall  f1-score   support

           0       0.66      0.97      0.79       100
           1       0.57      0.07      0.13        54

    accuracy                           0.66       154
   macro avg       0.62      0.52      0.46       154
weighted avg       0.63      0.66      0.56       154

In [633]:
print("=======================Accuracy Score using Feature Scaling========================================================")

print("Accuracy with out Feature Scaling is", ac)

print("Accuracy with Feature Scaling using Standard Scaler is", ac_sc)

print("Accuracy with Feature Scaling using Min Max Scaler is", ac_minmax)

print("Accuracy with Feature Scaling using Normalizer is", ac_norm)

=======================Accuracy Score using Feature Scaling========================================================
Accuracy with out Feature Scaling is 70.77922077922078
Accuracy with Feature Scaling using Standard Scaler is 70.77922077922078
Accuracy with Feature Scaling using Min Max Scaler is 71.42857142857143
Accuracy with Feature Scaling using Normalizer is 65.5844155844156

#### OBSERVATIONS:

1.  The accuracy of the model using Minmax scaler is the highest and the accuracy of the model using Normalizer is the lowest.

    ac_minmax > (ac = ac_sc) > ac_norm