#### Perceptron

1.  A perceptron can be defined as a single layered neural network unit.

2.  It can be defined as a single unit of the neural network model.

#### Problem Statement

1.  The main objective of the problem statement is to build a simple perceptron from the scratch for a student dataset and check whether the student has passed or failed based on the perceptron and even test on the new data.

#### Step 1: Import all the necessary libraries

In [1]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

#### OBSERVATIONS:

1.  numpy -------->  It is used to perform the mathematical operations on the arrays.

#### Step 2: Load the dataset

In [2]:
#### Load the data
data = pd.read_csv('data.csv')

In [3]:
data

   Hours_Studied  Attendance  Pass
0              2          40     0
1              3          50     0
2              4          60     0
3              5          65     1
4              6          70     1
5              7          80     1
6              8          90     1
7              9          95     1

#### OBSERVATIONS:

1.  The above dataset depicts about the student's details whether the student has passed or failed.

    (a.)    Hours_Studied ------------>  Number of hours studied by the student.

    (b.)    Attendance    ------------>  Attendance percentage of the students who have attended the class.

    (c.)    Pass          ------------>  It depicts about the status of the student whether pass or fail

            (i.)    1 ---------------->  Student has passed

            (ii.)   0 ---------------->  Student has failed.

#### Step 3: Create the Input features

In [4]:
#### define the input features
X = data.drop(columns=['Pass'])

In [5]:
X

   Hours_Studied  Attendance
0              2          40
1              3          50
2              4          60
3              5          65
4              6          70
5              7          80
6              8          90
7              9          95

In [6]:
#### Check the type of x
type(X)

pandas.DataFrame

#### OBSERVATIONS:

1.  The dataset is divided into input and output features.

    The input data has

        (a.)    Hours_Studied

        (b.)    Attendance

In [7]:
#### Convert the input into the numpy array
X = X.to_numpy()

In [8]:
X

array([[ 2, 40],
       [ 3, 50],
       [ 4, 60],
       [ 5, 65],
       [ 6, 70],
       [ 7, 80],
       [ 8, 90],
       [ 9, 95]])

In [9]:
#### Again check the type of X
type(X)

numpy.ndarray

#### OBSERVATIONS:

1.  X and Y are converted into numpy array because most of the mathematical calculations of machine learning are done using numpy array.

#### Step 4: define the output features

In [10]:
#### define the output features
Y = data['Pass']

In [11]:
Y

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
Name: Pass, dtype: int64

In [12]:
type(Y)

pandas.Series

In [13]:
#### Convert the series into numpy array
Y = Y.to_numpy()

In [14]:
Y

array([0, 0, 0, 1, 1, 1, 1, 1])

In [15]:
type(Y)

numpy.ndarray

#### OBSERVATIONS:

1.  The output feature has only Pass status whether the student has Pass/ Fail.

#### Step 5: Initialize the weights

In [16]:
#### Initialize the weights

weights = np.array([0.1,0.1])

In [17]:
weights

array([0.1, 0.1])

In [18]:
weights.dtype

dtype('float64')

#### OBSERVATIONS:

1.  As there are two inputs namely Hours_Studied, Atendance, so two weights have been initialized.

#### Step 6: Initilize the bias

In [19]:
#### Initialize the bias

bias = 0

In [20]:
bias

0

#### OBSERVATIONS:

1. Bias has been added to the inputs so that if all the input values are all zero, then bias will add some weightage to the output.

#### Step 7: Create the Activation Function

In [21]:
##### create the step activation function
def step_activation_function(x):
    #### if the input is above the threshold
    if(x >= 0):
        return(1)
    return(0)

In [22]:
#### call the step activation function
step_activation_function(5)

1

#### OBSERVATION:

1.  Here the step activation function is created.

2.  A step activation function is one of the simplest activation function used in Artificial Neural Networks that determines whether the neuron should fire or not.

3.  It has two values:---

    (a.)    1 ------------>  If the input value is above the threshold.

    (b.)    0 ------------>  If the input is below the threshold.

#### Step 8: Set the learning rate

In [23]:
#### determine the learning rate
learning_rate = 0.01

#### OBSERVATIONS:

1.  learning rate determines how much does the weights change.

#### Step 9: Train the Perceptron

In [24]:
#### Train the perceptron
for epoch in range(100):
    for i in range(len(X)):
        #### Calculate the weighted sum
        z = np.dot(X[i],weights)+bias
        #### Apply the activation function on the weighted sum
        predicted = step_activation_function(z)
        #### get the error
        error = Y[i] - predicted
        #### update the weighted sum and the bias
        weights = weights + (learning_rate*error*X[i])
        bias    = bias    + (learning_rate*error)

print("Weights is:", weights)
print("Bias    is:", bias)

Weights is: [ 0.71 -0.05]
Bias    is: -0.21000000000000005

#### OBSERVATIONS:

1.  The Perceptron is trained for 100 iterations.

2.  For each iteration, it is looped through each student record

    (a.)  Weighted sum is calculated for each student record.

    (b.)  Then activation function is applied on each input record to get the predicted output for each student record.

    (c.)  The error is calculated for each student record by finding the diference between the actual - predicted value.

    (d.)  The weights and the bias are updated using the formulas given above in the code.

#### Step 10: Predict whether the student has passed or failed based on the test data

In [25]:
#### define the test data
test_data = np.array([6, 75])

#### Calculate the weighted sum based on the test data
z = np.dot(test_data,weights) + bias
print(z)

#### Apply the step activation function of the weighted sum to get the predicted output
predicted = step_activation_function(z)
print("Predicted Output is:", predicted)

#### Student pass or fail
if(predicted == 1):
    print("Student will pass")
else:
    print("student will fail")

0.2999999999999944
Predicted Output is: 1
Student will pass

#### Step 11: Perform prediction on the series of the students marks

In [26]:
#### define the students marks
test_students = np.array([
    [2, 35],   # Likely Fail
    [4, 55],   # Borderline
    [6, 75],   # Likely Pass
    [8, 90]    # Likely Pass
])

for x in test_students:
    #### Calculate the weighted sum
    z = np.dot(x,weights) + bias
    print(z)
    #### Apply the step activation function on the test data
    predictions = step_activation_function(z)
    print(predictions)

    print(
        f"Hours={x[0]}, Attendance={x[1]} -> "
        f"{'Pass' if predictions == 1 else 'Fail'}"
    )

-0.5400000000000021
0
Hours=2, Attendance=35 -> Fail
-0.12000000000000374
0
Hours=4, Attendance=55 -> Fail
0.2999999999999944
1
Hours=6, Attendance=75 -> Pass
0.9699999999999943
1
Hours=8, Attendance=90 -> Pass

#### OBSERVATIONS:

1.  The students have been failed or passed based on the students marks given in each row based on the test data.