#### Fake News Classification

1.  The main objective of the problem statement is:---

    (a.)    to understand and analyze the fake news classification data

    (b.)    perform Logistic Regression and Support Vector Classifier on the dataset

    (c.)    predict the type of news for the new test data

    (d.)    get the accuracy of the model


#### Steps used in this Algorithm:---

1.  Import all the necessary libraries

2.  Download all the necessary NLTK lbraries

3.  Read the  Dataset

4.  Perform the Text Preprocessing Function

5.  Apply Cleaning

6.  Perform the Data Preprocessing Function

7.  Convert Text to Numerical Features (TF-IDF)

8.  Perform the Train-Test Split

9.  Train Logistic Regression Model

10. Train the Support Vector Classifier Model

11. Make Predictions for the model

12. Evaluate the Model

13. Test with Custom Sentence

#### Step 1: Import all the necessary libraries

In [192]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

import  nltk

from    nltk.tokenize   import  word_tokenize,sent_tokenize
from    nltk.corpus     import  stopwords
from    nltk.tokenize   import  RegexpTokenizer

from    sklearn.model_selection import  train_test_split
from    sklearn.preprocessing   import  StandardScaler
from    sklearn.linear_model    import  LogisticRegression
from    sklearn.svm             import  SVC
from    sklearn.metrics         import  accuracy_score

#### OBSERVATIONS:

1.  LogisticRegression -----------> It performs the binary classification problems and classifies whether the news is real or fake.

2.  SVC                -----------> It builds hyperplane and classifies the data into two different categories and detremines real/fake news.

#### Step 2: Download all the necessary NLTK lbraries

In [193]:
#### Download all the NLTK libraries
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

#### OBSERVATIONS:

1.  punkt_tab ----------->  It is a pre-defined tokenizer that is used to perform tokenization process.

2.  stopwords ----------->  It is used for the removal of all the stopwords from the text.

#### Step 3: Read the  Dataset

In [194]:
#### Load the dataset
df = pd.read_csv('train.csv')

In [195]:
df

       label                                               news
0      False  Says the Annies List political group supports ...
1       True  When did the decline of coal start? It started...
2       True  Hillary Clinton agrees with John McCain "by vo...
3      False  Health care reform legislation is likely to ma...
4       True  The economic turnaround started at the end of ...
...      ...                                                ...
10235   True  There are a larger number of shark attacks in ...
10236   True  Democrats have now become the party of the [At...
10237   True  Says an alternative to Social Security that op...
10238  False  On lifting the U.S. Cuban embargo and allowing...
10239  False  The Department of Veterans Affairs has a manua...

[10240 rows x 2 columns]

#### OBSERVATIONS:

1.  There are a total of 10240 records in the dataset.

2.  The dataset has two columns

    (a.)    news ----------> It has the new information in it

    (b.)    label ----------> It determines the type of new i.e True/False news

In [196]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10240 entries, 0 to 10239
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   10240 non-null  bool
 1   news    10240 non-null  str
dtypes: bool(1), str(1)
memory usage: 90.1 KB

#### Step 4: Perform the Text Preprocessing Function

In [197]:
#### define the function

#### define the function
def clean_news(text):
    #### convert the text into lower case
    text = text.lower()
    #### convert the text into words by performing word tokenization
    words = word_tokenize(text)
    #### convert the words in list into the text form
    words = ' '.join(words)
    #### create an object for RegexpTokenizer
    reg = RegexpTokenizer(r'\w+')
    #### apply the object of RegexpTokenizer to remove all the punctuations and the special symbols from the text
    ans = reg.tokenize(words)
    #### convert the text in lists to words
    ans = ' '.join(ans)
    return(ans)

#### Step 5: Apply Cleaning

In [198]:
#### define the function call
df['clean_news'] = df['news'].apply(clean_news)

In [199]:
df['clean_news']

0        says the annies list political group supports ...
1        when did the decline of coal start it started ...
2        hillary clinton agrees with john mccain by vot...
3        health care reform legislation is likely to ma...
4        the economic turnaround started at the end of ...
                               ...
10235    there are a larger number of shark attacks in ...
10236    democrats have now become the party of the atl...
10237    says an alternative to social security that op...
10238    on lifting the u s cuban embargo and allowing ...
10239    the department of veterans affairs has a manua...
Name: clean_news, Length: 10240, dtype: str

#### OBSERVATIONS:

1.  The text preprocessing function has been defined that will clean all the reviews from the dataset using clean_news function.

#### Step 6:  Perform the Data Preprocessing Function

In [200]:
#### Map the False as 1 and True as 0
from    sklearn.preprocessing import LabelEncoder

#### create an object for LabelEncoder
label = LabelEncoder()

#### using the object of label encoder, transform the labels
df['label'] = label.fit_transform(df['label'])

In [201]:
df

,label,news,clean_news
0,0,Says the Annies List political group supports ...,says the annies list political group supports ...
1,1,When did the decline of coal start? It started...,when did the decline of coal start it started ...
2,1,"Hillary Clinton agrees with John McCain ""by vo...",hillary clinton agrees with john mccain by vot...
3,0,Health care reform legislation is likely to ma...,health care reform legislation is likely to ma...
4,1,The economic turnaround started at the end of ...,the economic turnaround started at the end of ...
...,...,...,...
10235,1,There are a larger number of shark attacks in ...,there are a larger number of shark attacks in ...
10236,1,Democrats have now become the party of the [At...,democrats have now become the party of the atl...
10237,1,Says an alternative to Social Security that op...,says an alternative to social security that op...
10238,0,On lifting the U.S. Cuban embargo and allowing...,on lifting the u s cuban embargo and allowing ...
10239,0,The Department of Veterans Affairs has a manua...,the department of veterans affairs has a manua...

In [202]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10240 entries, 0 to 10239
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   label       10240 non-null  int64
 1   news        10240 non-null  str
 2   clean_news  10240 non-null  str
dtypes: int64(1), str(2)
memory usage: 240.1 KB

In [203]:
#### Map the 0(False) as 1 and 1(True) as 0 for identifying the real and the fake news
df['label'] = df['label'].map({0:1,1:0})

In [204]:
df

,label,news,clean_news
0,1,Says the Annies List political group supports ...,says the annies list political group supports ...
1,0,When did the decline of coal start? It started...,when did the decline of coal start it started ...
2,0,"Hillary Clinton agrees with John McCain ""by vo...",hillary clinton agrees with john mccain by vot...
3,1,Health care reform legislation is likely to ma...,health care reform legislation is likely to ma...
4,0,The economic turnaround started at the end of ...,the economic turnaround started at the end of ...
...,...,...,...
10235,0,There are a larger number of shark attacks in ...,there are a larger number of shark attacks in ...
10236,0,Democrats have now become the party of the [At...,democrats have now become the party of the atl...
10237,0,Says an alternative to Social Security that op...,says an alternative to social security that op...
10238,1,On lifting the U.S. Cuban embargo and allowing...,on lifting the u s cuban embargo and allowing ...
10239,1,The Department of Veterans Affairs has a manua...,the department of veterans affairs has a manua...

#### OBSERVATIONS:

1.  After applying the mapping operation, all the Fake news havve been labelled as 1 and all the real news have been labelled as 0.

In [205]:
#### Remove the news column from the dataset
df.drop(columns='news',inplace=True)

In [206]:
df

       label                                         clean_news
0          1  says the annies list political group supports ...
1          0  when did the decline of coal start it started ...
2          0  hillary clinton agrees with john mccain by vot...
3          1  health care reform legislation is likely to ma...
4          0  the economic turnaround started at the end of ...
...      ...                                                ...
10235      0  there are a larger number of shark attacks in ...
10236      0  democrats have now become the party of the atl...
10237      0  says an alternative to social security that op...
10238      1  on lifting the u s cuban embargo and allowing ...
10239      1  the department of veterans affairs has a manua...

[10240 rows x 2 columns]

#### OBSERVATIONS:

1.  All the datas in the news columns have been removed from the dataset.

In [207]:
#### Reorder the position of clean_news and label in the dataset

df = df[['clean_news','label']]

In [208]:
df

                                              clean_news  label
0      says the annies list political group supports ...      1
1      when did the decline of coal start it started ...      0
2      hillary clinton agrees with john mccain by vot...      0
3      health care reform legislation is likely to ma...      1
4      the economic turnaround started at the end of ...      0
...                                                  ...    ...
10235  there are a larger number of shark attacks in ...      0
10236  democrats have now become the party of the atl...      0
10237  says an alternative to social security that op...      0
10238  on lifting the u s cuban embargo and allowing ...      1
10239  the department of veterans affairs has a manua...      1

[10240 rows x 2 columns]

#### OBSERVATIONS:

1.  The clean_news and the label has been arranges in their correct position.

#### Step 7: Convert Text to Numerical Features (TF-IDF)

In [209]:
from sklearn.feature_extraction.text import TfidfVectorizer

#### create an object for TfidfVectorizer
tfidf = TfidfVectorizer()

#### using the object of Tfidf vectorizer, transform the text into the sparse matrix
X_sparse_matrix = tfidf.fit_transform(df['clean_news'])

In [210]:
X_sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 166001 stored elements and shape (10240, 12187)>

#### OBSERVATIONS:

1.  The text data has been converted into the sparse matrix containing 10240 words and 12187 vocabularies and stores only 166001 non zero words only.

In [211]:
#### determine the dependent variables
Y = df['label']

In [212]:
Y

0        1
1        0
2        0
3        1
4        0
        ..
10235    0
10236    0
10237    0
10238    1
10239    1
Name: label, Length: 10240, dtype: int64

In [213]:
#### determine the number of the count for each output categories
Y.value_counts()

label
0    5752
1    4488
Name: count, dtype: int64

#### OBSERVATIONS:

1.  There are 5752 real news and 4488 fake news in the dataset.

#### Step 8: Perform the Train-Test Split

In [214]:
#### Keep the input data in the form of sparse matrix

X_sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 166001 stored elements and shape (10240, 12187)>

#### OBSERVATIONS:

1.  For splitting the data into training and testing, the data for the input must be in sparse matrix. This is because

    (a.)    converting it into the numpy array means converting the sparse matrix into dense matrix which makes the data more complex

    (b.)    It even causes more huge dense memory causing it for crashing.

In [215]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test  = train_test_split(X_sparse_matrix,Y,test_size=0.2,random_state=42,stratify=Y)

In [216]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 132781 stored elements and shape (8192, 12187)>

In [217]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 33220 stored elements and shape (2048, 12187)>

In [218]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (8192, 12187)
Shape of the input testing  data is: (2048, 12187)

In [219]:
Y_train

6919     1
8829     0
732      0
3460     1
327      1
        ..
10060    0
4371     1
9320     1
3195     0
6927     1
Name: label, Length: 8192, dtype: int64

In [220]:
Y_test

10209    0
5636     0
5239     0
1747     0
9135     1
        ..
3167     0
5352     0
6679     1
7495     0
667      0
Name: label, Length: 2048, dtype: int64

In [221]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (8192,)
Shape of the output testing  data is: (2048,)

#### OBSERVATIONS:

1.  The dataset is divided into 

    (a.)    80 % of the training data -------------->  8192 records for training

    (b.)    20 % of the testing  data -------------->  2048 records for testing

#### Step 9: Train Logistic Regression Model

In [222]:
from sklearn.linear_model import LogisticRegression

#### create an object for Logistic Regression
log = LogisticRegression(max_iter=1000)

#### using the object for Logistic Regression, train the model
log.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

#### OBSERVATIONS:

1.  The object for Logistic Regression model has been made

2.  The model has been trained with the help of the training data.

#### Step 10: Train the Support Vector Classifier Model

In [223]:
from sklearn.svm import SVC

#### Create an object for SVC
svc = SVC(kernel='linear')

#### using the object of SVC, train the model
svc.fit(X_train, Y_train)

SVC(kernel='linear')

#### OBSERVATIONS:

1.  The object of SVC model has been created with kernel as linear means it can handle linear data

2.  Then the model has been trained with the help  of the training data.

#### Step 11: Make Predictions for the model

In [224]:
#### Make the predictions for the logistic regression
Y_pred_log = log.predict(X_test)

In [225]:
Y_pred_log

array([0, 0, 0, ..., 1, 0, 0], shape=(2048,))

In [226]:
#### Make the predictions for SVC
Y_pred_svc = svc.predict(X_test)

In [227]:
Y_pred_svc

array([0, 0, 0, ..., 1, 1, 0], shape=(2048,))

#### Step 12: Evaluate the Model

In [228]:
#### Evaluate the model for Logistic Regression

aclog = accuracy_score(Y_test, Y_pred_log)*100.0
print("Accuracy score for the Logistic Regression model is:", aclog)

Accuracy score for the Logistic Regression model is: 62.6953125

In [229]:
#### Evaluate the model for SVC

acsvc = accuracy_score(Y_test, Y_pred_svc)*100.0
print("Accuracy score for the Support Vector Classifier model is:", acsvc)

Accuracy score for the Support Vector Classifier model is: 61.71875

#### OBSERVATIONS:

1.  The accuracy score for Logistic Regression is 63 %

2.  The accuracy score for Support Vector Classifier is 61.7 %

3.  The accuracy score of logistic > svc . This is because

    (a.) This is a binary classification to predict whether the news is real or fake 

    (b.) Logistic Regression can work well on binary classification problems.

#### Step 13: Test with Custom Sentence

In [230]:
#### define the function
def predict_news(text):
    #### preprocess the text
    text = clean_news(text)
    #### transform the text
    transformed = tfidf.transform([text])

    #### perform the prediction on the test data
    print("Logistic Regression is:", log.predict(transformed)[0])
    print("Support Vector Classiier is:",svc.predict(transformed)[0])

#### call the function
predict_news("Breaking news: Government launches new digital policy")

Logistic Regression is: 1
Support Vector Classiier is: 1

#### OBSERVATIONS:

1.  As both the Logistic Regression and SVC produces the predicted output as 1.

2.  This indicates that the test news is a fake news.