#### SMS Spam Classification

1.  The main objective of the problem statement is :----

    (a.) to analyze the text data

    (b.) perform Multinomial Naive Bayes on the text data

    (c.) predict whether the text message is Ham / Spam

#### Steps used in this Algorithm:---

1.	Import all the necessary libraries

2.	Load the Dataset

3.	Perform Data Preprocessing

4.	Divide the dataset into independent and dependent variables

5.	Split dataset into train and test

6.    Convert text into numerical features using Bag Of Words

7.	Initialize Naive Bayes model

8.	Train the model

9.	Make predictions

10.	Evaluate model

11.	Testing on New Data

#### Step 1: Import all the necessary libraries

In [592]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

import  nltk

from    nltk.tokenize   import  word_tokenize
from    nltk.corpus     import  stopwords
from    nltk.tokenize   import  RegexpTokenizer

from    sklearn.model_selection         import  train_test_split
from    sklearn.preprocessing           import  StandardScaler
from    sklearn.feature_extraction.text import  TfidfVectorizer
from    sklearn.metrics                 import  accuracy_score
from    sklearn.naive_bayes             import  MultinomialNB

#### OBSERVATIONS:

1.  MultinomialNB ----------> It deals with the test so as to perform the text classification.

#### Step 2: Load the Dataset

In [593]:
#### Load the dataset
df = pd.read_csv('spam.csv',encoding='latin-1')

In [594]:
df

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

#### OBSERVATIONS:

1.  The above dataset has two columns. They are

    (a.)    text -------->  text data

    (b.)    label ------->  label information either ham / spam

#### Step 3: Perform Data Preprocessing

In [595]:
#### Remove all the unnecessary columns from the dataset

df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [596]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

#### OBSERVATIONS:

1.  All the unnecessary columns have been removed from the dataset

In [597]:
#### Rename the column to the proper names
df.rename(columns={"v1":"label", "v2":"text"},inplace=True)

In [598]:
df

     label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

#### OBSERVATIONS:

1.  The 'v1' and 'v2' column has been renamed to their proper names 'label' and text' respectively.

In [599]:
#### Put the columns in their proper position
df=df[['text','label']]

In [600]:
df

                                                   text label
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568              Will Ì_ b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5572 rows x 2 columns]

#### OBSERVATIONS:

1.  All the columns are now in the proper position.

In [601]:
#### Check for the missing values

df.isnull().sum()

text     0
label    0
dtype: int64

#### OBSERVATIONS:

1.  There are no missing values in the dataset.

In [602]:
#### Check for the class distribution
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64

#### OBSERVATIONS:

1.  The dataset has 4825 ham messages and 747 spam messages. So the dataset is good.

In [603]:
#### Convert the labels to numbers
from sklearn.preprocessing import LabelEncoder

#### create an object for Label Encoder
label = LabelEncoder()

#### using the object of LabelEncoder, transform the data
df['label'] = label.fit_transform(df['label'])

In [604]:
df

                                                   text  label
0     Go until jurong point, crazy.. Available only ...      0
1                         Ok lar... Joking wif u oni...      0
2     Free entry in 2 a wkly comp to win FA Cup fina...      1
3     U dun say so early hor... U c already then say...      0
4     Nah I don't think he goes to usf, he lives aro...      0
...                                                 ...    ...
5567  This is the 2nd time we have tried 2 contact u...      1
5568              Will Ì_ b going to esplanade fr home?      0
5569  Pity, * was in mood for that. So...any other s...      0
5570  The guy did some bitching but I acted like i'd...      0
5571                         Rofl. Its true to its name      0

[5572 rows x 2 columns]

#### OBSERVATIONS:

1.  After performing label encoding, the labels of 'spam' message has been converted into 1 and the labels of 'ham' message has been converted into 0.

#### Step 4: Divide the dataset into independent and dependent variables

In [605]:
#### independent variables
X = df['text']

In [606]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: text, Length: 5572, dtype: str

In [607]:
#### dependent features
Y = df['label']

In [608]:
Y

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5572, dtype: int64

#### OBSERVATIONS:

1.  The dataset has been divided into the independent and dependent features.

#### Step 5: Split dataset into train and test

In [609]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [610]:
X_train

184                            Going on nothing great.bye
2171                        I wont. So wat's wit the guys
5422              Ok k..sry i knw 2 siva..tats y i askd..
4113    Where are you ? What do you do ? How can you s...
4588         Have you not finished work yet or something?
                              ...
1932                            Jus finished avatar nigro
5316                         Jus finish watching tv... U?
2308    Moby Pub Quiz.Win a å£100 High Street prize if...
1903    Free entry in 2 a weekly comp for a chance to ...
763     Nothing but we jus tot u would ask cos u ba gu...
Name: text, Length: 4457, dtype: str

In [611]:
X_test

2826    Oh right, ok. I'll make sure that i do loads o...
3695                       I am in tirupur.  call you da.
3906               No that just means you have a fat head
575     You have won ?1,000 cash or a ?2,000 prize! To...
2899    Come aftr  &lt;DECIMAL&gt; ..now i m cleaning ...
                              ...
854     Stop the story. I've told him i've returned it...
5044    We have sent JD for Customer Service cum Accou...
2015    Just re read it and I have no shame but tell m...
3381    Well, I meant as opposed to my drunken night o...
785     She was supposed to be but couldn't make it, s...
Name: text, Length: 1115, dtype: str

In [612]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (4457,)
Shape of the input testing  data is: (1115,)

In [613]:
Y_train

184     0
2171    0
5422    0
4113    0
4588    0
       ..
1932    0
5316    0
2308    1
1903    1
763     0
Name: label, Length: 4457, dtype: int64

In [614]:
Y_test

2826    0
3695    0
3906    0
575     1
2899    0
       ..
854     0
5044    0
2015    0
3381    0
785     0
Name: label, Length: 1115, dtype: int64

In [615]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (4457,)
Shape of the output testing  data is: (1115,)

#### OBSERVATIONS:

1.  The dataset is divided into 

    (a.)    80 % training data ------------>  4457 records

    (b.)    20 % testing data  ------------>  1115 records

#### Step 6: Convert text into numerical features using Bag Of Words

In [616]:
from sklearn.feature_extraction.text import TfidfVectorizer

#### create an object for TfidfVectorizer
tfidf = TfidfVectorizer()

#### using the object of TfidfVectorizer, transform the text
X_train_vectorized = tfidf.fit_transform(X_train)

In [617]:
X_train_vectorized

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 58998 stored elements and shape (4457, 7701)>

In [618]:
X_test_vectorized = tfidf.transform(X_test)

In [619]:
X_test_vectorized

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13881 stored elements and shape (1115, 7701)>

#### OBSERVATIONS:

1.  The input text has been converted into sparse matrix which is a numerical representation of the words.

#### Step 7: Initialize Naive Bayes model

In [620]:
from sklearn.naive_bayes import MultinomialNB

#### Create an object for MultinomialNB
multi_NB = MultinomialNB()

#### OBSERVATIONS:

1.  The object for Multinomial Naive Bayes model has been created.

#### Step 8: Train the model

In [621]:
#### using the object of MultinomialNB, train the model
multi_NB.fit(X_train_vectorized, Y_train)

MultinomialNB()

#### OBSERVATIONS:

1.  The Multinomial Naive Bayes model has been trained with the help of training data.

#### Step 9: Make predictions

In [622]:
#### Make predictions
Y_pred_multinb = multi_NB.predict(X_test_vectorized)

In [623]:
Y_pred_multinb

array([0, 0, 0, ..., 0, 0, 0], shape=(1115,))

#### OBSERVATIONS:

1.  The predictions have been made for the test data.

#### Step 10: Evaluate model

In [624]:
from sklearn.metrics import accuracy_score

ac = accuracy_score(Y_test, Y_pred_multinb)*100.0

print("Accuracy of the model is:", ac)

Accuracy of the model is: 96.05381165919282

#### OBSERVATIONS:

1.  The accuracy of the Multinomial Naive Bayes model using SMS Spam Classification dataset is 96.05 % which is very high.

2.  So the model is working fine.

#### Step 11: Testing on New Data

In [625]:
#### test data
new_sms = [
    "FREE entry into our prize draw. WIN cash now. Call immediately."
]

#### transform the test data
transformed = tfidf.transform(new_sms)
print(transformed)

#### perform the predictions on the test data
predictions = multi_NB.predict(transformed)
print(predictions)

#### check the probabilities of each class
prob = multi_NB.predict_proba(transformed)
print(prob)

if(predictions[0] == 1):
    print("Spam")
else:
    print("Ham")

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 11 stored elements and shape (1, 7701)>
  Coords	Values
  (0, 1600)	0.18730877972525578
  (0, 1670)	0.29235072238150506
  (0, 2428)	0.3285163470647305
  (0, 2597)	0.3760693221516066
  (0, 2962)	0.23783994384406348
  (0, 3588)	0.4027295782038637
  (0, 3683)	0.3507543507587521
  (0, 4806)	0.1960951576179144
  (0, 4969)	0.26177694842179183
  (0, 5387)	0.30015709012876673
  (0, 7464)	0.30204804893184223
[1]
[[0.07969104 0.92030896]]
Spam