
###  Annotated follow-along guide: Compute descriptive statistics with Python

This notebook contains the code used in the following instructional video: Compute descriptive statistics with Python.

###  Introduction

Throughout this notebook, we will practice computing descriptive statistics to explore and summarize a dataset. Before getting started, watch the associated instructional video and complete the in-video question. All of the code we will be implementing and related instructions are contained in this notebook.

###  Overview

Earlier in the program, you learned about the process of exploratory data analysis, or EDA, from discovering to presenting your data. Whenever a data professional works with a new dataset, the first step is to understand the context of the data during the discovering stage. Often, this involves discussing the data with project stakeholders and reading documentation about the dataset and the data collection process. After that, the data professional moves on to data cleaning and addresses issues like missing data, incorrect values, and irrelevant data. Computing descriptive stats is a common step to take after data cleaning.

In this notebook, we will use descriptive stats to get a basic understanding of the literacy rate data for each district in your education dataset.

###  Import packages and libraries

Before getting started, we will need to import all the required libraries and extensions. Throughout the course, we will be using pandas and numpy for operations and matplotlib for plotting.

In [115]:
### import all the necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [116]:
### load the dataset

education_districtwise = pd.read_csv('education_districtwise.csv')

In [117]:
education_districtwise

        DISTNAME STATNAME  BLOCKS  VILLAGES  CLUSTERS  TOTPOPULAT  OVERALL_LI
0     DISTRICT32   STATE1      13       391       104    875564.0       66.92
1    DISTRICT649   STATE1      18       678       144   1015503.0       66.93
2    DISTRICT229   STATE1       8        94        65   1269751.0       71.21
3    DISTRICT259   STATE1      13       523       104    735753.0       57.98
4    DISTRICT486   STATE1       8       359        64    570060.0       65.00
..           ...      ...     ...       ...       ...         ...         ...
675  DISTRICT522  STATE29      37       876       137   5296396.0       78.05
676  DISTRICT498  STATE29      64      1458       230   4042191.0       56.06
677  DISTRICT343  STATE29      59      1117       216   3483648.0       65.05
678  DISTRICT130  STATE29      51       993       211   3522644.0       66.16
679  DISTRICT341  STATE29      41       783       185   2798214.0       65.46

[680 rows x 7 columns]

### OBSERVATIONS:

1.  The above dataset depicts about the literacy status of the total population per district per state in every block, cluster and village.

In [118]:
### get the top five rows of the dataset

education_districtwise.head(10)

      DISTNAME STATNAME  BLOCKS  VILLAGES  CLUSTERS  TOTPOPULAT  OVERALL_LI
0   DISTRICT32   STATE1      13       391       104    875564.0       66.92
1  DISTRICT649   STATE1      18       678       144   1015503.0       66.93
2  DISTRICT229   STATE1       8        94        65   1269751.0       71.21
3  DISTRICT259   STATE1      13       523       104    735753.0       57.98
4  DISTRICT486   STATE1       8       359        64    570060.0       65.00
5  DISTRICT323   STATE1      12       523        96   1070144.0       64.32
6  DISTRICT114   STATE1       6       110        49    147104.0       80.48
7  DISTRICT438   STATE1       7       134        54    143388.0       74.49
8  DISTRICT610   STATE1      10       388        80    409576.0       65.97
9  DISTRICT476   STATE1      11       361        86    555357.0       69.90

### OBSERVATIONS:

1. The above dataset depicts about the top ten literacy status of the population per district per state in every block, village and cluster.

In [119]:
### To get the descriptive statistics about the dataset

education_districtwise.describe()

           BLOCKS     VILLAGES    CLUSTERS    TOTPOPULAT  OVERALL_LI
count  680.000000   680.000000  680.000000  6.340000e+02  634.000000
mean    10.760294   874.614706  121.226471  1.899024e+06   73.395189
std      9.585360   622.711657   94.040172  1.547475e+06   10.098460
min      1.000000     6.000000    1.000000  7.948000e+03   37.220000
25%      5.000000   390.750000   56.750000  8.226940e+05   66.437500
50%      8.000000   785.500000  101.000000  1.564392e+06   73.490000
75%     13.000000  1204.250000  162.500000  2.587520e+06   80.815000
max     66.000000  3963.000000  592.000000  1.105413e+07   98.760000

### OBSERVATIONS:

1. The above dataset depicts about the descriptive summary statistics for every numerical column used in the dataset.

In [120]:
education_districtwise['OVERALL_LI'].describe()

count    634.000000
mean      73.395189
std       10.098460
min       37.220000
25%       66.437500
50%       73.490000
75%       80.815000
max       98.760000
Name: OVERALL_LI, dtype: float64

### OBSERVATIONS:

1. The above dataset depicts about the statistical summary about the numerical column 'OVERALL_LI'.

In [121]:
education_districtwise

        DISTNAME STATNAME  BLOCKS  VILLAGES  CLUSTERS  TOTPOPULAT  OVERALL_LI
0     DISTRICT32   STATE1      13       391       104    875564.0       66.92
1    DISTRICT649   STATE1      18       678       144   1015503.0       66.93
2    DISTRICT229   STATE1       8        94        65   1269751.0       71.21
3    DISTRICT259   STATE1      13       523       104    735753.0       57.98
4    DISTRICT486   STATE1       8       359        64    570060.0       65.00
..           ...      ...     ...       ...       ...         ...         ...
675  DISTRICT522  STATE29      37       876       137   5296396.0       78.05
676  DISTRICT498  STATE29      64      1458       230   4042191.0       56.06
677  DISTRICT343  STATE29      59      1117       216   3483648.0       65.05
678  DISTRICT130  STATE29      51       993       211   3522644.0       66.16
679  DISTRICT341  STATE29      41       783       185   2798214.0       65.46

[680 rows x 7 columns]

In [122]:
education_districtwise['STATNAME'].describe()

count         680
unique         36
top       STATE21
freq           75
Name: STATNAME, dtype: object

### OBSERVATIONS:

1.  As STATNAME is a categorical column, so here we get the categorical summary statistics about the column in the dataset.

In [123]:
### Calculate the range for the column 'OVERALL_LI'

education_districtwise.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680 entries, 0 to 679
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DISTNAME    680 non-null    object
 1   STATNAME    680 non-null    object
 2   BLOCKS      680 non-null    int64
 3   VILLAGES    680 non-null    int64
 4   CLUSTERS    680 non-null    int64
 5   TOTPOPULAT  634 non-null    float64
 6   OVERALL_LI  634 non-null    float64
dtypes: float64(2), int64(3), object(2)
memory usage: 37.3+ KB

In [124]:
### To find out the range for the column 'OVERALL_LI' in education_districtwise


min_literacy_rate = education_districtwise['OVERALL_LI'].min()

print("Minimum literacy rate of Overall literacy is:", min_literacy_rate)

Minimum literacy rate of Overall literacy is: 37.22

In [125]:

max_literacy_rate = education_districtwise['OVERALL_LI'].max()

print("Maximum literacy rate of Overall literacy is:", max_literacy_rate)

Maximum literacy rate of Overall literacy is: 98.76

In [126]:
### Range of the column 'OVERALL_LI'

range = max_literacy_rate - min_literacy_rate

print("Difference between the minimum and maximum literacy rate is:", range)

Difference between the minimum and maximum literacy rate is: 61.540000000000006