#### Handling Missing Values in Employee Salary Dataset

In [296]:
##### import all the necessary libraries

import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

In [297]:
#### Load the dataset

df = pd.read_csv("salary_data_with_nulls.csv")

In [298]:
df

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               NaN   37731.0
3               2.0       NaN
4               2.2   39891.0
5               2.9   56642.0
6               3.0       NaN
7               NaN   60150.0
8               3.2   54445.0
9               3.2   64445.0
10              3.7   57189.0
11              3.9   63218.0
12              4.0       NaN
13              4.0   55794.0
14              NaN   56957.0
15              4.5   61111.0
16              4.9   67938.0
17              5.1   66029.0
18              5.3       NaN
19              5.9   81363.0
20              6.0   93940.0
21              6.8   91738.0
22              NaN   98273.0
23              7.9       NaN
24              8.2  113812.0
25              8.7  109431.0
26              9.0  105582.0
27              9.5  116969.0
28              NaN  112635.0
29             10.5       NaN

#### OBSERVATIONS:

1.  The above dataset is a employees salary dataset with the salary earned by the employees based on the years of experience.

2.  This dataset contains the NULL Values in both the YearsExperience column and in the Salary column.

In [299]:
#### Replacing all the NULL Values in YearsExperience with the mean value of it

df['YearsExpnew'] = df['YearsExperience'].fillna(df['YearsExperience'].mean())

In [300]:
df

    YearsExperience    Salary  YearsExpnew
0               1.1   39343.0        1.100
1               1.3   46205.0        1.300
2               NaN   37731.0        5.072
3               2.0       NaN        2.000
4               2.2   39891.0        2.200
5               2.9   56642.0        2.900
6               3.0       NaN        3.000
7               NaN   60150.0        5.072
8               3.2   54445.0        3.200
9               3.2   64445.0        3.200
10              3.7   57189.0        3.700
11              3.9   63218.0        3.900
12              4.0       NaN        4.000
13              4.0   55794.0        4.000
14              NaN   56957.0        5.072
15              4.5   61111.0        4.500
16              4.9   67938.0        4.900
17              5.1   66029.0        5.100
18              5.3       NaN        5.300
19              5.9   81363.0        5.900
20              6.0   93940.0        6.000
21              6.8   91738.0        6.800
22              NaN   98273.0        5.072
23              7.9       NaN        7.900
24              8.2  113812.0        8.200
25              8.7  109431.0        8.700
26              9.0  105582.0        9.000
27              9.5  116969.0        9.500
28              NaN  112635.0        5.072
29             10.5       NaN       10.500

In [301]:
### Drop the column 'YearsExperience' having the NULL Values

df.drop(columns = 'YearsExperience', inplace=True)

In [302]:
df['YearsExperience'] = df['YearsExpnew']

In [303]:
df

      Salary  YearsExpnew  YearsExperience
0    39343.0        1.100            1.100
1    46205.0        1.300            1.300
2    37731.0        5.072            5.072
3        NaN        2.000            2.000
4    39891.0        2.200            2.200
5    56642.0        2.900            2.900
6        NaN        3.000            3.000
7    60150.0        5.072            5.072
8    54445.0        3.200            3.200
9    64445.0        3.200            3.200
10   57189.0        3.700            3.700
11   63218.0        3.900            3.900
12       NaN        4.000            4.000
13   55794.0        4.000            4.000
14   56957.0        5.072            5.072
15   61111.0        4.500            4.500
16   67938.0        4.900            4.900
17   66029.0        5.100            5.100
18       NaN        5.300            5.300
19   81363.0        5.900            5.900
20   93940.0        6.000            6.000
21   91738.0        6.800            6.800
22   98273.0        5.072            5.072
23       NaN        7.900            7.900
24  113812.0        8.200            8.200
25  109431.0        8.700            8.700
26  105582.0        9.000            9.000
27  116969.0        9.500            9.500
28  112635.0        5.072            5.072
29       NaN       10.500           10.500

In [304]:
### Drop the column 'YearsExperience' having the NULL Values

df.drop(columns = 'YearsExpnew', inplace=True)

In [305]:
df

      Salary  YearsExperience
0    39343.0            1.100
1    46205.0            1.300
2    37731.0            5.072
3        NaN            2.000
4    39891.0            2.200
5    56642.0            2.900
6        NaN            3.000
7    60150.0            5.072
8    54445.0            3.200
9    64445.0            3.200
10   57189.0            3.700
11   63218.0            3.900
12       NaN            4.000
13   55794.0            4.000
14   56957.0            5.072
15   61111.0            4.500
16   67938.0            4.900
17   66029.0            5.100
18       NaN            5.300
19   81363.0            5.900
20   93940.0            6.000
21   91738.0            6.800
22   98273.0            5.072
23       NaN            7.900
24  113812.0            8.200
25  109431.0            8.700
26  105582.0            9.000
27  116969.0            9.500
28  112635.0            5.072
29       NaN           10.500

In [306]:
#### Replace all the NULL Values in Salary column with the median value of it

df['Salary_med'] = df['Salary'].fillna(df['Salary'].median())

In [307]:
df

      Salary  YearsExperience  Salary_med
0    39343.0            1.100     39343.0
1    46205.0            1.300     46205.0
2    37731.0            5.072     37731.0
3        NaN            2.000     63831.5
4    39891.0            2.200     39891.0
5    56642.0            2.900     56642.0
6        NaN            3.000     63831.5
7    60150.0            5.072     60150.0
8    54445.0            3.200     54445.0
9    64445.0            3.200     64445.0
10   57189.0            3.700     57189.0
11   63218.0            3.900     63218.0
12       NaN            4.000     63831.5
13   55794.0            4.000     55794.0
14   56957.0            5.072     56957.0
15   61111.0            4.500     61111.0
16   67938.0            4.900     67938.0
17   66029.0            5.100     66029.0
18       NaN            5.300     63831.5
19   81363.0            5.900     81363.0
20   93940.0            6.000     93940.0
21   91738.0            6.800     91738.0
22   98273.0            5.072     98273.0
23       NaN            7.900     63831.5
24  113812.0            8.200    113812.0
25  109431.0            8.700    109431.0
26  105582.0            9.000    105582.0
27  116969.0            9.500    116969.0
28  112635.0            5.072    112635.0
29       NaN           10.500     63831.5

In [308]:
#### Drop the column Salary having the NULL Values 

df.drop(columns = 'Salary', inplace=True,axis=1)

In [309]:
df['Salary'] = df['Salary_med']

In [310]:
#### Drop the column Salary having the NULL Values 

df.drop(columns = 'Salary_med', inplace=True,axis=1)

In [311]:
df

    YearsExperience    Salary
0             1.100   39343.0
1             1.300   46205.0
2             5.072   37731.0
3             2.000   63831.5
4             2.200   39891.0
5             2.900   56642.0
6             3.000   63831.5
7             5.072   60150.0
8             3.200   54445.0
9             3.200   64445.0
10            3.700   57189.0
11            3.900   63218.0
12            4.000   63831.5
13            4.000   55794.0
14            5.072   56957.0
15            4.500   61111.0
16            4.900   67938.0
17            5.100   66029.0
18            5.300   63831.5
19            5.900   81363.0
20            6.000   93940.0
21            6.800   91738.0
22            5.072   98273.0
23            7.900   63831.5
24            8.200  113812.0
25            8.700  109431.0
26            9.000  105582.0
27            9.500  116969.0
28            5.072  112635.0
29           10.500   63831.5

#### OBSERVATIONS:

1.  All the NULL Values in the YearsExperience and Salary has been replaced by the 


     (a.)   mean value  of the YearsExperience

     (b.)   median value of the Salary

In [312]:
df['Category'] = 'A'

In [313]:
####make every second row as NULL

df.loc[::2,'Category'] = np.nan

In [314]:
df

    YearsExperience    Salary Category
0             1.100   39343.0      NaN
1             1.300   46205.0        A
2             5.072   37731.0      NaN
3             2.000   63831.5        A
4             2.200   39891.0      NaN
5             2.900   56642.0        A
6             3.000   63831.5      NaN
7             5.072   60150.0        A
8             3.200   54445.0      NaN
9             3.200   64445.0        A
10            3.700   57189.0      NaN
11            3.900   63218.0        A
12            4.000   63831.5      NaN
13            4.000   55794.0        A
14            5.072   56957.0      NaN
15            4.500   61111.0        A
16            4.900   67938.0      NaN
17            5.100   66029.0        A
18            5.300   63831.5      NaN
19            5.900   81363.0        A
20            6.000   93940.0      NaN
21            6.800   91738.0        A
22            5.072   98273.0      NaN
23            7.900   63831.5        A
24            8.200  113812.0      NaN
25            8.700  109431.0        A
26            9.000  105582.0      NaN
27            9.500  116969.0        A
28            5.072  112635.0      NaN
29           10.500   63831.5        A

In [315]:
#### Find the mode value of the Category column

mode_val = df['Category'].mode()[0]

print(mode_val)

A

In [316]:
#### Reaplce all the NULL Value with the mode value of the Ctageory column

df['Category'] = df['Category'].fillna(df['Category'].mode()[0])

In [317]:
df

    YearsExperience    Salary Category
0             1.100   39343.0        A
1             1.300   46205.0        A
2             5.072   37731.0        A
3             2.000   63831.5        A
4             2.200   39891.0        A
5             2.900   56642.0        A
6             3.000   63831.5        A
7             5.072   60150.0        A
8             3.200   54445.0        A
9             3.200   64445.0        A
10            3.700   57189.0        A
11            3.900   63218.0        A
12            4.000   63831.5        A
13            4.000   55794.0        A
14            5.072   56957.0        A
15            4.500   61111.0        A
16            4.900   67938.0        A
17            5.100   66029.0        A
18            5.300   63831.5        A
19            5.900   81363.0        A
20            6.000   93940.0        A
21            6.800   91738.0        A
22            5.072   98273.0        A
23            7.900   63831.5        A
24            8.200  113812.0        A
25            8.700  109431.0        A
26            9.000  105582.0        A
27            9.500  116969.0        A
28            5.072  112635.0        A
29           10.500   63831.5        A

#### OBSERVATIONS:

1.  All the NULL Values in the category column has been filled with the mode value of it.