#### Handling Categorical Values

In [183]:
import   numpy              as  np
import   pandas             as  pd
import   matplotlib.pyplot  as  plt
import   seaborn            as  sns

In [184]:
#### Load the dataset

df = pd.read_csv("employees_data.csv")

In [185]:
df

   EmployeeID  Gender Department  Education  Salary
0           1    Male         IT  Bachelors   60000
1           2  Female         HR    Masters   65000
2           3  Female    Finance  Bachelors   70000
3           4    Male         IT        PhD   80000
4           5  Female         HR  Bachelors   62000
5           6    Male    Finance    Masters   72000
6           7  Female         IT        PhD   85000
7           8    Male         HR  Bachelors   58000
8           9  Female    Finance    Masters   77000
9          10    Male         IT  Bachelors   69000

#### OBSERVATIONS:

1.  The above dataset explains about all the basic details of the employees like ID, Gender, Department, Education and Salary.

In [186]:
#### perform the label encoding on Gender and Department

from  sklearn.preprocessing   import  LabelEncoder

#### create an object for LabelEncoder

label = LabelEncoder()

#### using the object for LabelEncoder, transform the Gender and Department column

df['Gender'] = label.fit_transform(df[['Gender']])

c:\Users\DELL\Desktop\Complete_Data_Science\vens\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [187]:
df

   EmployeeID  Gender Department  Education  Salary
0           1       1         IT  Bachelors   60000
1           2       0         HR    Masters   65000
2           3       0    Finance  Bachelors   70000
3           4       1         IT        PhD   80000
4           5       0         HR  Bachelors   62000
5           6       1    Finance    Masters   72000
6           7       0         IT        PhD   85000
7           8       1         HR  Bachelors   58000
8           9       0    Finance    Masters   77000
9          10       1         IT  Bachelors   69000

#### OBSERVATIONS:

1.  The Label Encoding has been applied on the Gender column and after that

    (a.)  Female value ----------->   0

    (b.)  Male value   ----------->   1

In [188]:
df['Department'].value_counts()

Department
IT         4
HR         3
Finance    3
Name: count, dtype: int64

In [189]:
df['Department'] = label.fit_transform(df[['Department']])

c:\Users\DELL\Desktop\Complete_Data_Science\vens\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [190]:
df

   EmployeeID  Gender  Department  Education  Salary
0           1       1           2  Bachelors   60000
1           2       0           1    Masters   65000
2           3       0           0  Bachelors   70000
3           4       1           2        PhD   80000
4           5       0           1  Bachelors   62000
5           6       1           0    Masters   72000
6           7       0           2        PhD   85000
7           8       1           1  Bachelors   58000
8           9       0           0    Masters   77000
9          10       1           2  Bachelors   69000

In [191]:
df['Department'].value_counts()

Department
2    4
1    3
0    3
Name: count, dtype: int64

#### OBSERVATIONS:

1.  The Label Encoding has been applied on the Department column and after that

    (a.)  Finance      ----------->   0

    (b.)  HR           ----------->   1

    (c.)  IT           ----------->   2

In [192]:
#### Display the dataset

df

   EmployeeID  Gender  Department  Education  Salary
0           1       1           2  Bachelors   60000
1           2       0           1    Masters   65000
2           3       0           0  Bachelors   70000
3           4       1           2        PhD   80000
4           5       0           1  Bachelors   62000
5           6       1           0    Masters   72000
6           7       0           2        PhD   85000
7           8       1           1  Bachelors   58000
8           9       0           0    Masters   77000
9          10       1           2  Bachelors   69000

In [193]:
#### Apply One-Hot Encoding on Education column


onehot_education = pd.get_dummies(df, columns = ['Education'], drop_first=True)

In [194]:
onehot_education

   EmployeeID  Gender  Department  Salary  Education_Masters  Education_PhD
0           1       1           2   60000              False          False
1           2       0           1   65000               True          False
2           3       0           0   70000              False          False
3           4       1           2   80000              False           True
4           5       0           1   62000              False          False
5           6       1           0   72000               True          False
6           7       0           2   85000              False           True
7           8       1           1   58000              False          False
8           9       0           0   77000               True          False
9          10       1           2   69000              False          False

#### OBSERVATIONS:

1.  Here one hot encoding has been applied on the 'Education' columns and the values present in the 'Education' column has been converted into seperate columns.

In [195]:
from sklearn.preprocessing import OneHotEncoder

# Reload dataset
df = pd.read_csv("employees_data.csv")

# Initialize encoder
ohe = OneHotEncoder(sparse_output=False)

# Transform Department column
encoded = ohe.fit_transform(df[['Department']])

# Convert to DataFrame
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out())

# Merge with original data
df_final = pd.concat([df.drop('Department', axis=1), encoded_df], axis=1)

print(df_final.head())

   EmployeeID  Gender  Education  Salary  Department_Finance  Department_HR  \
0           1    Male  Bachelors   60000                 0.0            0.0
1           2  Female    Masters   65000                 0.0            1.0
2           3  Female  Bachelors   70000                 1.0            0.0
3           4    Male        PhD   80000                 0.0            0.0
4           5  Female  Bachelors   62000                 0.0            1.0

   Department_IT
0            1.0
1            0.0
2            0.0
3            1.0
4            0.0